### ISSUE TITLE
Disable on Twigmo (mobile site)

### ISSUE THREAD

**Issue by bbbenji** [apache/incubator-pagespeed-ngx#1003]
We are using http://twigmo.com as our mobile site. Pagespeed is causing issues with our forms of payments and I would like to disable PS there.

I assumed that adding the following .js into the mobile site would help:

```
twg.initSettings = twg.func.wrap(twg.initSettings, function(srcFunc) {
srcFunc();
settings.requestUrl += '&ModPagespeed=off';
});
```

But it did not and after some testing, adding the query `?ModPagespeed=off` manually to any url does not work either.

**Comment by jmarantz** [comment]
What problems does it cause on your mobile payment site?

-Josh

**Comment by bbbenji** [comment]
The issue seemed to be that the url ended up having CSS in it. Not sure exactly what was causing it in Pagespeed but it seems the .js posted above has started working. We disabled PS on the mobile version and everything works just fine.

When I have time to do some testing on our test server I will be sure to post more info. But for now I do not want to touch production if it's working as intended.
