### ISSUE TITLE
Scripts loaded by require.js are not being optimized by IPRO

### ISSUE THREAD

**Issue by ArtemGordinsky** [apache/incubator-pagespeed-ngx#1007]
Most of the scripts on our website are loaded by require.js, and they are not getting optimized. Instead, they are being returned with cache-control set to «max-age=300» as shown in [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=platinumlist.net&tab=desktop) (even though Nginx sets this value to 1 year when PageSpeed is disabled). By the way, images, CSS files and non-require.js scripts are being optimized properly.
All resources are loaded over https, and here is [the website](https://platinumlist.net) itself.

These are the settings from nginx.conf:

```
pagespeed on;
pagespeed Domain *.platinumlist.net;
pagespeed FileCachePath /var/cache/nginx/ngx_pagespeed_cache;
pagespeed RewriteLevel PassThrough;
pagespeed EnableFilters rewrite_css,flatten_css_imports,rewrite_javascript,include_js_source_maps,rewrite_images,remove_comments,collapse_whitespace,extend_cache,in_place_optimize_for_browser;
pagespeed LoadFromFile "https://platinumlist.net/"
                       "/var/www/...";
pagespeed InPlaceResourceOptimization on;
```

Is there something wrong with my setup or are require.js scripts deemed "dangerous" by the rewriting mechanism and thus skipped? By the way, the scripts have been minified manually using a different tool, mod_pagespeed did not minify them.

**Comment by jeffkaufman** [comment]
Scripts loaded by `require.js` on your website are being optimized by PageSpeed:

```
$ curl -s https://platinumlist.net/dist/vendor/swipe.js | wc -c
5273
$ curl -s https://platinumlist.net/dist/vendor/swipe.js?PageSpeed=off | wc -c
5307
```

On the other hand, the only change it's making to the body is removing the source map url:

```
$ icdiff <(curl https://platinumlist.net/dist/vendor/swipe.js?PageSpeed=off) \
          <(curl https://platinumlist.net/dist/vendor/swipe.js)
"//# sourceMappingURL=swipe.js.map" is removed
...

And the header change is also not an improvement:

```
- Cache-Control: max-age=31536000
- Cache-Control: public
+ Cache-Control: max-age=300
```

I need to look into this.

**Comment by ArtemGordinsky** [comment]
@jeffkaufman Sorry, I should've compared the sizes myself instead of using my eyes.
I have noticed the same cache-control issue with images loaded via AJAX. I guess it could be related to https? Any way I could help debugging this further?
