### ISSUE TITLE
broken image load

### ISSUE THREAD

**Issue by slavonnet** [apache/incubator-pagespeed-ngx#1039]
Error is - "Content-Length:1"

Remote Address:87.255.28.227:80
Request URL:http://www.open-bs.ru/upload/iblock/b17/docr11c.jpg
Request Method:GET
Status Code:206 Partial Content
Response Headers
view source
Cache-Control:max-age=315360000
Connection:keep-alive
Content-Length:1
Content-Range:bytes 87345-87345/146008
Content-Type:image/jpeg
Date:Thu, 05 Nov 2015 11:29:24 GMT
ETag:"562f853f-23a58"
Expires:Thu, 31 Dec 2037 23:55:55 GMT
Last-Modified:Tue, 27 Oct 2015 14:07:59 GMT
Server:nginx/1.9.6
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
Cache-Control:max-age=0
Connection:keep-alive
Cookie:BITRIX_SM_SOUND_LOGIN_PLAYED=Y; _ym_uid=1446574888687918216; BITRIX_SM_LOGIN=admin; BITRIX_SM_DSC=44; BITRIX_SM_LAST_SETTINGS=; PHPSESSID=f8362788a911b734ee0724983c85bb74; BITRIX_SM_GUEST_ID=974740; BITRIX_SM_LAST_VISIT=05.11.2015+13%3A55%3A03; BITRIX_SM_LAST_ADV=5; _ga=GA1.2.1883704549.1446452510
Host:www.open-bs.ru
If-Range:"562f853f-23a58"
Range:bytes=87345-87345
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
Name
docr11c.jpg
1 requests ❘ 17.4 KB transferred ❘ Finish: 63 ms
Console
Emulation
Rendering

Preserve log
.
docr11c.jpg:1 GET http://www.open-bs.ru/upload/iblock/b17/docr11c.jpg net::ERR_CONTENT_LENGTH_MISMATCH
.

**Comment by slavonnet** [comment]
bug present only if add

thread_pool default threads=32 max_queue=65536;
aio threads=default;

to nginx

**Comment by oschaaf** [comment]
I could reproduce the bad content length with http://www.open-bs.ru/upload/iblock/b17/docr11c.jpg, but now I can't, did you fix something?

**Comment by slavonnet** [comment]
bug present only if add

thread_pool default threads=32 max_queue=65536;
aio threads=default;

to nginx

**Comment by hex0id** [comment]
I confirm bug presents with thread_pool. In my case it was thread_pool iopool threads=32 max_queue=65536;

**Comment by oschaaf** [comment]
Our system tests fail as well with this configured:
```
thread_pool default threads=32 max_queue=65536;
aio threads=default;
```

At first sight, something seems wrong with range requests and IPRO

**Comment by oschaaf** [comment]
I've been looking into this. I think the bug has a relation with the IPRO recording flow indicating that we need to have the filter response buffered, but the IPRO body filter may not be doing the right thing for that when threading is enabled.
One interesting observation is that when the gzip filter runs after us and does process our buffers, the response will turn out to be OK. So to fix this, we may have to look at what the gzip filter is doing that we don't in the IPRO recording flow.

**Comment by jmarantz** [comment]
What exactly is it that the threadpool in nginx does?  I had thought nginx
was mostly running without threads; only a few processes and lots of
asynchronous networking.

Is it adding a few threads listening to sockets in each process, similar to
Apache's worker mpm?

-Josh

**Comment by oschaaf** [comment]
@jmarantz See https://www.nginx.com/blog/thread-pools-boost-performance-9x/

I think the thread pools are used to execute wrappers around blocking system calls (readfile, sendfile).
I'm not sure how often thread pools are used in practice, but we're not behaving nicely currently when they are enabled. I think it would be good to at least warn upon seeing a configuration that enables thread pools - or be compatible with thread pool usage if it isn't a huge amount of work?

**Comment by hex0id** [comment]
in addition - I was totally fine before upgrading nginx / pagespeed.
versions listed above.

On Saturday, February 27, 2016, Otto van der Schaaf <
notifications@github.com> wrote:

> @jmarantz <https://github.com/jmarantz> See
> https://www.nginx.com/blog/thread-pools-boost-performance-9x/
>
> I think the thread pools are used to execute wrappers around blocking
> system calls (readfile, sendfile).
> I'm not sure how often thread pools are used in practice, but we're not
> behaving nicely currently when they are enabled. I think it would be good
> to at least warn upon seeing a configuration that enables thread pools - or
> be compatible with thread pool usage if it isn't a huge amount of work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pagespeed/ngx_pagespeed/issues/1039#issuecomment-189736018>
> .
>


-- 
Regards, Alex.

**Comment by oschaaf** [comment]
I ran a few manual tests with ngx_pagespeed 1.10.33.6 + nginx's thread pools:
- this seems to work ok on nginx's 1.8 branch
- but this combination seems to break with nginx's master branch

So I think either something is wrong in the way we set up our build in `config` for newer nginx versions (https://github.com/pagespeed/ngx_pagespeed/commit/09f53881de3bfe548d73d928a53283e72ca06310) , or nginx made a change that broke ngx_pagespeed when having thread pools set up.

**Comment by oschaaf** [comment]
So I'd thought I'd take a peek at the history of nginx's copy filter module to see what changed, and noticed this commit from yesterday:
https://github.com/nginx/nginx/commit/00fcc6a987f1d45a9eac91242de7e3527451242e

I was on a slightly older commit :-(
Sounds like something that may fix this, I'll try that.

**Comment by oschaaf** [comment]
Indeed nginx/nginx@00fcc6a seems to fix the problem for me. @slavonnet @hex0id do you still experience trouble  if you run a version of nginx that includes https://github.com/nginx/nginx/commit/00fcc6a987f1d45a9eac91242de7e3527451242e when using `thread_pool`?
