### ISSUE TITLE
Hint preload incompatibilities

### ISSUE THREAD

**Issue by darylounet** [apache/incubator-pagespeed-ngx#1504]
Hi,
I'm using PageSpeed 1.12.34-3 with NGiNX 1.12.2. I wanted to activate the new hint_preload_subresources filter but :
- I have to disable memcached to see "link" headers (I've already tried to purge cache & restart memcached)
- once memcached disabled, I get "link" headers but the prioritize_critical_css filter isn't working anymore

Is there some kind of incompatibilities with the hint_preload_subresources filter I should know ?

Thanks.

**Comment by alearq** [comment]
I can't seem to get the "hint_preload_subresources" to work at all. But a guess is we're all hitting this issue:
https://github.com/apache/incubator-pagespeed-ngx/issues/1408

**Comment by oschaaf** [comment]
@alearq I concur. Closing this as a duplicate to so we track this in one place.
