### ISSUE TITLE
Nginx, brotli, ssl combination crashes nginx

### ISSUE THREAD

**Issue by nolybom** [apache/incubator-pagespeed-ngx#1518]
Debugged a little deeper and can confirm @Volodymyr Lupu 's (centminmod) catch that the combination of brotli, ssl and pagespeed causes huge use of RAM and CPU which leads to a site crash.

This thread on centminmod describes it best:

https://community.centminmod.com/threads/nginx-uses-all-resources-and-then-crashes-when-pagespeed-is-enabled.13490/#post-57450

One interesting thing is that when brotli and pagespeed are both enabled and only http sites are reloaded then everything seems fine. But the moment the https site comes to the game with a fresh reload the problems start.

Log file lists worker process xxxxx exited on signal 11 and 9.

---

Not sure if related to the above but...

**pagespeed off; vs. pagespeed unplugged; issue**

My pagespeed version is X-Page-Speed: 1.12.34.3-0 and toggling between 

`pscontrol off` and `pscontrol on`

changes the entry `pagespeed unplugged;` to `pagespeed on;`.
So far so fine...now the https sites load normal but phpmyadmin still crashes.

`pagespeed off;` 

in the pagespespeedadmin.conf (or adding it directly to phpmyadmin-ssl.conf) makes phpmyadmin  and all sites load normal.

**Comment by nolybom** [comment]
Edit: updating pagespeed now to the current version and hope this will fix the latter described issue which could be also related to centminmod.

**Comment by oschaaf** [comment]
Reading the upstream report, I wonder: Is the https/brotli issue still relevant with 1.13.35.1? Or is that issue fixed in that release?

Also: Unplugged is new in 1.13.35.1, earlier versions wont understand it, as you observed.

**Comment by nolybom** [comment]
Yes, the Is the https/brotli/ps issue is still relevant with 1.13.35.1.

**Comment by Lofesa** [comment]
Hi
I had these combination w/o issues. nginx 1.13.7 pagespeed 1.13.35.1 (w/ patch for s-maxage issue) and sites w/ Letsencrypt certificates, brotli, centos 7.4....
For nginx, pagespeed and brotli I have rpm packages if some one need for testing.

**Comment by nolybom** [comment]
@Lofesa thank you for participating. Can i please have a look?

**Comment by Lofesa** [comment]
[nginx-1.13.7-1.el7.centos.ngx.x86_64.zip](https://github.com/pagespeed/ngx_pagespeed/files/1581909/nginx-1.13.7-1.el7.centos.ngx.x86_64.zip)
[nginx-module-brotli-0.6-1.13.7.x86_64.zip](https://github.com/pagespeed/ngx_pagespeed/files/1581910/nginx-module-brotli-0.6-1.13.7.x86_64.zip)
[nginx-module-pagespeed-1.13.35.1-beta.1.13.7.1.el7.centos.ngx.x86_64.zip](https://github.com/pagespeed/ngx_pagespeed/files/1581911/nginx-module-pagespeed-1.13.35.1-beta.1.13.7.1.el7.centos.ngx.x86_64.zip)

These are rpm files. I have changed the file extension to zip for upload here

**Comment by dtzWill** [comment]
I was encountering a bug that sounds very similar to this, but found it was fixed when using this version of ngx_brotli: https://github.com/eustas/ngx_brotli/commit/47550a25d07363f8eb87ef901b2de5883c46352b .

(and brotli 1.0.2).

Not sure at all if this helps but just wanted to share in case it helps fix things for someone :).

**Comment by oschaaf** [comment]
Thanks @dtzWill

**Comment by dtzWill** [comment]
@oschaaf you're welcome :). Did that fix things for you "too"?

**Comment by oschaaf** [comment]
Well I can see that the change in the brotli module you pointed out adresses a potential problem, which could very well be related to the crasher reported here -- though I cant prove it. It's pretty helpful that it is cross linked here. Let's close this issue and see if it gets reported / reopened again.

**Comment by nolybom** [comment]
@dtzWill Thank you very much for the hint!
I have tested it and can confirm so far that the bug is fixed. (y)
