### ISSUE TITLE
Cannot install - issues with ngx_pagespeed.o

### ISSUE THREAD

**Issue by REPTILEHAUS** [apache/incubator-pagespeed-ngx#1522]
I have a docker environment that i have deployed a couple of times and it has always worked except now when provisioning a new server the same old reliable dockerfile now has errors relating to ngx_pagespeed.o  any ideas whats happening here

nginx v: 1.13.3
pagespeed: 1.12.34.3-stable

```
	-o objs/addon/src/ngx_pagespeed.o \
	/tmp/incubator-pagespeed-ngx-1.12.34.3-stable/src/ngx_pagespeed.cc
objs/Makefile:1929: recipe for target 'objs/addon/src/ngx_pagespeed.o' failed
make[1]: Leaving directory '/tmp/nginx-1.13.3'
Makefile:8: recipe for target 'build' failed
cc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 4
make: *** [build] Error 2
```

**Comment by oschaaf** [comment]
Could the build process be running out of memory?

**Comment by REPTILEHAUS** [comment]
Im not sure, Ill scale up the vm now and revert back with the result.

**Comment by REPTILEHAUS** [comment]
Scaled up the instance and its working as it should, really should have checked that first. thanks man.

**Comment by oschaaf** [comment]
No problem, happy to hear its working now!
