### ISSUE TITLE
nginx/1.12.1 make error ‘NGX_CONF_MULTI’ was not declared in this scope NGX_HTTP_SRV_CONF|NGX_CONF_TAKE1|NGX_CONF_MULTI|

### ISSUE THREAD

**Issue by dominatos** [apache/incubator-pagespeed-ngx#1531]
nginx/1.12.1 make error:
/usr/src/incubator-pagespeed-ngx-release-1.10.33.5-beta/src/ngx_pagespeed.cc:685:39: error: ‘NGX_CONF_MULTI’ was not declared in this scope
     NGX_HTTP_MAIN_CONF|NGX_CONF_TAKE1|NGX_CONF_MULTI|
                                       ^
/usr/src/incubator-pagespeed-ngx-release-1.10.33.5-beta/src/ngx_pagespeed.cc:692:38: error: ‘NGX_CONF_MULTI’ was not declared in this scope
     NGX_HTTP_SRV_CONF|NGX_CONF_TAKE1|NGX_CONF_MULTI|
                                      ^
/usr/src/incubator-pagespeed-ngx-release-1.10.33.5-beta/src/ngx_pagespeed.cc:700:56: error: ‘NGX_CONF_MULTI’ was not declared in this scope
     NGX_HTTP_LOC_CONF|NGX_HTTP_LIF_CONF|NGX_CONF_TAKE1|NGX_CONF_MULTI|
                                                        ^
make[1]: *** [objs/addon/src/ngx_pagespeed.o] Error 1
make[1]: Leaving directory `/usr/src/incubator-pagespeed-ngx-release-1.10.33.5-beta/nginx-1.12.1'
make: *** [build] Error 2

**Comment by oschaaf** [comment]
This was fixed a long time ago. Please retry with a later version.

**Comment by dominatos** [comment]
what is the latest stable build?

**Comment by oschaaf** [comment]
https://www.modpagespeed.com/doc/release_notes#release_1.12.34.3-stable
