### ISSUE TITLE
configure: error: module ngx_pagespeed requires the pagespeed optimization library.

### ISSUE THREAD

**Issue by chaihongjun** [apache/incubator-pagespeed-ngx#1533]
I've done these steps:
```
You need to separately download the pagespeed library:
     $ cd /root/lnmp/src/ngx_pagespeed-1.13.35.2-stable
     $ wget https://dl.google.com/dl/page-speed/psol/1.13.35.2-x64.tar.gz
     $ tar -xzvf 1.13.35.2-x64.tar.gz # expands to psol/
```
but,
configure: error: module ngx_pagespeed requires the pagespeed optimization library.

My server：
Centos:6.9
nginx:1.12.2

**Comment by stevenzhu25** [comment]
#1545

**Comment by stevenzhu25** [comment]
#1532 same error

**Comment by stevenzhu25** [comment]
@chaihongjun 
我已经解决那问题了。安装一下 “libuuid-devel” 然后再装就好了
Issue solved. Just install libuuid-devel on your system.

Thanks.

**Comment by chaihongjun** [comment]
@stevenzhu25  恩，我也看到了，报错是一样的。多谢哦！！！！

**Comment by chaihongjun** [comment]
close

**Comment by ac1982** [comment]
on Ubuntu 16.04, the lib named "`uuid-dev`"
`sudo apt-get install uuid-dev`

**Comment by uhlhosting** [comment]
This is not working on centos 8.

**Comment by leonardocxavier** [comment]
not work on debian 11
