### ISSUE TITLE
ngx_pagespeed 1.13.35.2-x64 dynamic module compile failed

### ISSUE THREAD

**Issue by thaomon** [apache/incubator-pagespeed-ngx#1534]
Hello, I am having problems adding the ngx_pagespeed module for my nginx 1.13.8, hope you help.

I did the following:

sudo yum install wget curl unzip gcc-c ++ pcre-devel zlib-devel

Then I went to my nginx 1.13.8 directory

cd /usr/local/vpssim/nginx-1.13.8/src/http/modules

sudo wget https://github.com/pagespeed/ngx_pagespeed/archive/master.zip

sudo unzip master.zip

sudo mv incubator-pagespeed-ngx-master ngx_pagespeed

cd ngx_pagespeed

sudo wget https://dl.google.com/dl/page-speed/psol/1.13.35.2-x64.tar.gz

sudo tar -xzvf 1.13.35.2-x64.tar.gz

cd /usr/local/vpssim/nginx-1.13.8

/ usr / local / vpssim / /http -log-path = / var / log / nginx / access.log --pid-path = / var / run / nginx.pid

I get the error:

Đang cấu hình các mô tả động khác
Thêm module in /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed
mod_pagespeed_dir = / usr / local / vpssim / nginx-1.13.8 / src / http / modules / ngx_pagespeed / psol / include
build_from_source = false
Kiểm tra tìm psol ... không tìm thấy
./configure: lỗi: ngx_pagespeed module cần thiết các trang văn phòng optimization.
Look in /usr/local/vpssim/nginx-1.13.8/objs/autoconf.err for more details.

And here is the autoconf.err file

----------------------------------------
checking for C compiler

----------------------------------------
checking for gcc -pipe switch

----------------------------------------
checking for -Wl,-E switch

----------------------------------------
checking for gcc builtin atomic operations

----------------------------------------
checking for C99 variadic macros

----------------------------------------
checking for gcc variadic macros

----------------------------------------
checking for gcc builtin 64 bit byteswap

----------------------------------------
checking for unistd.h

----------------------------------------
checking for inttypes.h

----------------------------------------
checking for limits.h

----------------------------------------
checking for sys/filio.h

objs/autotest.c:3:23: fatal error: sys/filio.h: No such file or directory
 #include <sys/filio.h>
                       ^
compilation terminated.
----------

#include <sys/filio.h>

int main(void) {
    return 0;
}

----------
cc -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for sys/param.h

----------------------------------------
checking for sys/mount.h

----------------------------------------
checking for sys/statvfs.h

----------------------------------------
checking for crypt.h

----------------------------------------
checking for epoll

----------------------------------------
checking for EPOLLRDHUP

----------------------------------------
checking for EPOLLEXCLUSIVE

objs/autotest.c: In function 'main':
objs/autotest.c:9:43: error: 'EPOLLEXCLUSIVE' undeclared (first use in this function)
                       ee.events = EPOLLIN|EPOLLEXCLUSIVE;
                                           ^
objs/autotest.c:9:43: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/epoll.h>

int main(void) {
    int efd = 0, fd = 0;
                      struct epoll_event ee;
                      ee.events = EPOLLIN|EPOLLEXCLUSIVE;
                      ee.data.ptr = NULL;
                      epoll_ctl(efd, EPOLL_CTL_ADD, fd, &ee);
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for O_PATH

----------------------------------------
checking for sendfile()

----------------------------------------
checking for sendfile64()

----------------------------------------
checking for sys/prctl.h

----------------------------------------
checking for prctl(PR_SET_DUMPABLE)

----------------------------------------
checking for prctl(PR_SET_KEEPCAPS)

----------------------------------------
checking for capabilities

----------------------------------------
checking for crypt_r()

----------------------------------------
checking for sys/vfs.h

----------------------------------------
checking for poll()

----------------------------------------
checking for /dev/poll

objs/autotest.c:4:25: fatal error: sys/devpoll.h: No such file or directory
 #include <sys/devpoll.h>
                         ^
compilation terminated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/devpoll.h>

int main(void) {
    int  n, dp; struct dvpoll  dvp;
                  dp = 0;
                  dvp.dp_fds = NULL;
                  dvp.dp_nfds = 0;
                  dvp.dp_timeout = 0;
                  n = ioctl(dp, DP_POLL, &dvp);
                  if (n == -1) return 1;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for kqueue

objs/autotest.c:4:23: fatal error: sys/event.h: No such file or directory
 #include <sys/event.h>
                       ^
compilation terminated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/event.h>

int main(void) {
    (void) kqueue();
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for crypt()

/tmp/ccV1pHwX.o: In function `main':
autotest.c:(.text+0xf): undefined reference to `crypt'
collect2: error: ld returned 1 exit status
----------

#include <sys/types.h>
#include <unistd.h>

int main(void) {
    crypt("test", "salt");;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for crypt() in libcrypt

----------------------------------------
checking for F_READAHEAD

objs/autotest.c: In function 'main':
objs/autotest.c:7:14: error: 'F_READAHEAD' undeclared (first use in this function)
     fcntl(0, F_READAHEAD, 1);;
              ^
objs/autotest.c:7:14: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <fcntl.h>

int main(void) {
    fcntl(0, F_READAHEAD, 1);;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for posix_fadvise()

----------------------------------------
checking for O_DIRECT

----------------------------------------
checking for F_NOCACHE

objs/autotest.c: In function 'main':
objs/autotest.c:7:14: error: 'F_NOCACHE' undeclared (first use in this function)
     fcntl(0, F_NOCACHE, 1);;
              ^
objs/autotest.c:7:14: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <fcntl.h>

int main(void) {
    fcntl(0, F_NOCACHE, 1);;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for directio()

objs/autotest.c: In function 'main':
objs/autotest.c:8:17: error: 'DIRECTIO_ON' undeclared (first use in this function)
     directio(0, DIRECTIO_ON);;
                 ^
objs/autotest.c:8:17: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/types.h>
                  #include <sys/fcntl.h>

int main(void) {
    directio(0, DIRECTIO_ON);;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for statfs()

----------------------------------------
checking for statvfs()

----------------------------------------
checking for dlopen()

/tmp/ccWSIX5q.o: In function `main':
autotest.c:(.text+0xf): undefined reference to `dlopen'
autotest.c:(.text+0x1e): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
----------

#include <sys/types.h>
#include <unistd.h>
#include <dlfcn.h>

int main(void) {
    dlopen(NULL, RTLD_NOW | RTLD_GLOBAL); dlsym(NULL, "");
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for dlopen() in libdl

----------------------------------------
checking for sched_yield()

----------------------------------------
checking for sched_setaffinity()

----------------------------------------
checking for SO_SETFIB

objs/autotest.c: In function 'main':
objs/autotest.c:7:31: error: 'SO_SETFIB' undeclared (first use in this function)
     setsockopt(0, SOL_SOCKET, SO_SETFIB, NULL, 0);
                               ^
objs/autotest.c:7:31: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>

int main(void) {
    setsockopt(0, SOL_SOCKET, SO_SETFIB, NULL, 0);
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for SO_REUSEPORT

----------------------------------------
checking for SO_ACCEPTFILTER

objs/autotest.c: In function 'main':
objs/autotest.c:7:31: error: 'SO_ACCEPTFILTER' undeclared (first use in this function)
     setsockopt(0, SOL_SOCKET, SO_ACCEPTFILTER, NULL, 0);
                               ^
objs/autotest.c:7:31: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>

int main(void) {
    setsockopt(0, SOL_SOCKET, SO_ACCEPTFILTER, NULL, 0);
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for SO_BINDANY

objs/autotest.c: In function 'main':
objs/autotest.c:7:31: error: 'SO_BINDANY' undeclared (first use in this function)
     setsockopt(0, SOL_SOCKET, SO_BINDANY, NULL, 0);
                               ^
objs/autotest.c:7:31: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>

int main(void) {
    setsockopt(0, SOL_SOCKET, SO_BINDANY, NULL, 0);
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for IP_TRANSPARENT

----------------------------------------
checking for IP_BINDANY

objs/autotest.c: In function 'main':
objs/autotest.c:8:31: error: 'IP_BINDANY' undeclared (first use in this function)
     setsockopt(0, IPPROTO_IP, IP_BINDANY, NULL, 0);
                               ^
objs/autotest.c:8:31: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>
                  #include <netinet/in.h>

int main(void) {
    setsockopt(0, IPPROTO_IP, IP_BINDANY, NULL, 0);
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for IP_BIND_ADDRESS_NO_PORT

objs/autotest.c: In function 'main':
objs/autotest.c:8:31: error: 'IP_BIND_ADDRESS_NO_PORT' undeclared (first use in this function)
     setsockopt(0, IPPROTO_IP, IP_BIND_ADDRESS_NO_PORT, NULL, 0);
                               ^
objs/autotest.c:8:31: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>
                  #include <netinet/in.h>

int main(void) {
    setsockopt(0, IPPROTO_IP, IP_BIND_ADDRESS_NO_PORT, NULL, 0);
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for IP_RECVDSTADDR

objs/autotest.c: In function 'main':
objs/autotest.c:8:31: error: 'IP_RECVDSTADDR' undeclared (first use in this function)
     setsockopt(0, IPPROTO_IP, IP_RECVDSTADDR, NULL, 0);
                               ^
objs/autotest.c:8:31: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>
                  #include <netinet/in.h>

int main(void) {
    setsockopt(0, IPPROTO_IP, IP_RECVDSTADDR, NULL, 0);
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for IP_SENDSRCADDR

objs/autotest.c: In function 'main':
objs/autotest.c:8:31: error: 'IP_SENDSRCADDR' undeclared (first use in this function)
     setsockopt(0, IPPROTO_IP, IP_SENDSRCADDR, NULL, 0);
                               ^
objs/autotest.c:8:31: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>
                  #include <netinet/in.h>

int main(void) {
    setsockopt(0, IPPROTO_IP, IP_SENDSRCADDR, NULL, 0);
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for IP_PKTINFO

----------------------------------------
checking for IPV6_RECVPKTINFO

----------------------------------------
checking for TCP_DEFER_ACCEPT

----------------------------------------
checking for TCP_KEEPIDLE

----------------------------------------
checking for TCP_FASTOPEN

----------------------------------------
checking for TCP_INFO

----------------------------------------
checking for accept4()

----------------------------------------
checking for eventfd()

----------------------------------------
checking for int size

----------------------------------------
checking for long size

----------------------------------------
checking for long long size

----------------------------------------
checking for void * size

----------------------------------------
checking for uint32_t

----------------------------------------
checking for uint64_t

----------------------------------------
checking for sig_atomic_t

----------------------------------------
checking for sig_atomic_t size

----------------------------------------
checking for socklen_t

----------------------------------------
checking for in_addr_t

----------------------------------------
checking for in_port_t

----------------------------------------
checking for rlim_t

----------------------------------------
checking for uintptr_t

----------------------------------------
checking for system byte ordering

----------------------------------------
checking for size_t size

----------------------------------------
checking for off_t size

----------------------------------------
checking for time_t size

----------------------------------------
checking for AF_INET6

----------------------------------------
checking for setproctitle()

/tmp/ccrZOj2a.o: In function `main':
autotest.c:(.text+0xf): undefined reference to `setproctitle'
collect2: error: ld returned 1 exit status
----------

#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>

int main(void) {
    setproctitle("test");;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for pread()

----------------------------------------
checking for pwrite()

----------------------------------------
checking for pwritev()

----------------------------------------
checking for sys_nerr

/tmp/ccnVJMFp.o: In function `main':
autotest.c:(.text+0x6): warning: `sys_nerr' is deprecated; use `strerror' or `strerror_r' instead
135
----------------------------------------
checking for localtime_r()

----------------------------------------
checking for posix_memalign()

----------------------------------------
checking for memalign()

----------------------------------------
checking for mmap(MAP_ANON|MAP_SHARED)

----------------------------------------
checking for mmap("/dev/zero", MAP_SHARED)

----------------------------------------
checking for System V shared memory

----------------------------------------
checking for POSIX semaphores

/tmp/ccNZuqOS.o: In function `main':
autotest.c:(.text+0x1a): undefined reference to `sem_init'
autotest.c:(.text+0x32): undefined reference to `sem_destroy'
collect2: error: ld returned 1 exit status
----------

#include <sys/types.h>
#include <unistd.h>
#include <semaphore.h>

int main(void) {
    sem_t  sem;
                  if (sem_init(&sem, 1, 0) == -1) return 1;
                  sem_destroy(&sem);;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for POSIX semaphores in libpthread

----------------------------------------
checking for struct msghdr.msg_control

----------------------------------------
checking for ioctl(FIONBIO)

----------------------------------------
checking for struct tm.tm_gmtoff

----------------------------------------
checking for struct dirent.d_namlen

objs/autotest.c: In function 'main':
objs/autotest.c:8:28: error: 'struct dirent' has no member named 'd_namlen'
     struct dirent  dir; dir.d_namlen = 0;
                            ^
objs/autotest.c:9:41: error: 'struct dirent' has no member named 'd_namlen'
                   printf("%d", (int) dir.d_namlen);
                                         ^
----------

#include <sys/types.h>
#include <unistd.h>
#include <dirent.h>
                  #include <stdio.h>

int main(void) {
    struct dirent  dir; dir.d_namlen = 0;
                  printf("%d", (int) dir.d_namlen);
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for struct dirent.d_type

----------------------------------------
checking for sysconf(_SC_NPROCESSORS_ONLN)

----------------------------------------
checking for sysconf(_SC_LEVEL1_DCACHE_LINESIZE)

----------------------------------------
checking for openat(), fstatat()

----------------------------------------
checking for getaddrinfo()

----------------------------------------
checking for psol

/bin/ld: cannot find -luuid
collect2: error: ld returned 1 exit status
----------

#include <sys/types.h>
#include <unistd.h>

#include "pagespeed/kernel/base/string.h"
#include "pagespeed/kernel/base/string_writer.h"
#include "pagespeed/kernel/base/null_message_handler.h"
#include "pagespeed/kernel/html/html_parse.h"
#include "pagespeed/kernel/html/html_writer_filter.h"

int main() {
    

  GoogleString output_buffer;
  net_instaweb::StringWriter write_to_string(&output_buffer);

  net_instaweb::NullMessageHandler handler;
  net_instaweb::HtmlParse html_parse(&handler);
  net_instaweb::HtmlWriterFilter html_writer_filter(&html_parse);

  html_writer_filter.set_writer(&write_to_string);
  html_parse.AddFilter(&html_writer_filter);

  html_parse.StartParse("http:example.com");
  html_parse.ParseText(
      "<html ><body ><h1 >Test</h1 ><p>Test Text</p></body></html>\n");
  html_parse.FinishParse();

  printf("parsed as: %s", output_buffer.c_str());
    return 0;
}

----------
cc -D_GLIBCXX_USE_CXX11_ABI=0 --std=c++11 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include/third_party/chromium/src -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include/third_party/google-sparsehash/src/src -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include/third_party/grpc/src/include -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include/third_party/protobuf/src/src -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include/third_party/re2/src -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include/out/Release/obj/gen -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include/out/Release/obj/gen/protoc_out/instaweb -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include/third_party/apr/src/include -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include/third_party/aprutil/src/include -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include/third_party/apr/gen/arch/linux/x64/include -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/include/url -o objs/autotest objs/autotest.cc /usr/local/vpssim/nginx-1.13.8/src/http/modules/ngx_pagespeed/psol/lib/Release/linux/x64/pagespeed_automatic.a -lstdc++ -lrt -pthread -lm -luuid
----------

**Comment by oschaaf** [comment]
You are missing libuuid-devel, see https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source for how to install

**Comment by thaomon** [comment]
I thank you very much, my problem was okay, but I got a new problem.
I followed the tutorial here. https://www.digitalocean.com/community/tutorials/how-to-add-ngx_pagespeed-to-nginx-on-centos-7

Go to the following section: sudo ln -s /usr/local/vpssim/nginx-1.13.8/conf/ / etc / nginx

then I get the error "ln: failed to create symbolic link '/ etc / nginx / conf': File exists
"

Please help me, I'm not good at programming
