### ISSUE TITLE
debian 9  checking for psol ... not found

### ISSUE THREAD

**Issue by ooogooo** [apache/incubator-pagespeed-ngx#1548]
adding module in /home/nginx/ngx_cache_purge-2.3
 + ngx_http_cache_purge_module was configured
adding module in /home/nginx/headers-more-nginx-module-0.33
 + ngx_http_headers_more_filter_module was configured
adding module in /home/nginx/incubator-pagespeed-ngx-1.13.35.2-stable
mod_pagespeed_dir=/home/nginx/incubator-pagespeed-ngx-1.13.35.2-stable/psol/include
build_from_source=false
checking for psol ... not found
./configure: error: module ngx_pagespeed requires the pagespeed optimization library.
Look in /home/nginx/nginx-1.13.10/objs/autoconf.err for more details.
make: *** No rule to make target 'install'.  Stop.

/nginx-1.13.10/objs/autoconf.err

789   GoogleString output_buffer;
790   net_instaweb::StringWriter write_to_string(&output_buffer);
791  
792   net_instaweb::NullMessageHandler handler;
793   net_instaweb::HtmlParse html_parse(&handler);
794   net_instaweb::HtmlWriterFilter html_writer_filter(&html_parse);
795  
796   html_writer_filter.set_writer(&write_to_string);
797   html_parse.AddFilter(&html_writer_filter);
798  
799   html_parse.StartParse("http:example.com");
800   html_parse.ParseText(
801     ¦ "<html ><body ><h1 >Test</h1 ><p>Test Text</p></body></html>\n");
802   html_parse.FinishParse();
803  
804   printf("parsed as: %s", output_buffer.c_str());
805     return 0;
806 }
807  
808 ----------
809 cc -Wno-deprecated-declarations -D_GLIBCXX_USE_CXX11_ABI=0 --std=c++11 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -I /home/nginx/incubato -I
810 ----------  

sh---------------------------------------------------------

#bin/bash

##install dependencies
#sudo apt install -y zlibc zlib1g build-essential zlib1g-dev libpcre3 libpcre3-dev libssl-dev libxslt1-dev libxml2-dev libgd2-xpm-dev libgeoip-dev libgoogle-perftools-dev libperl-dev

#mkdir -p /var/run/nginx-cache && chown nginx:nginx /var/run/nginx-cache
#mkdir -p /var/run/nginx-cache/nginx-proxy-temp-cache && chown nginx:nginx /var/run/nginx-cache/nginx-proxy-temp-cache

#groupadd nginx
#useradd -g nginx -s /sbin/nologin -M nginx

#nginx version
#http://nginx.org/download/nginx-1.13.10.tar.gz
NGINX_VERSION=1.13.10

#openssl version
#https://www.openssl.org/source/openssl-1.1.0h.tar.gz
OPENSSL_VERSION=1.1.0h

#ngx_pagespeed version
#https://github.com/apache/incubator-pagespeed-ngx/archive/v1.13.35.2-stable.tar.gz
NPS_VERSION=1.13.35.2

#Cache Purge module
#https://github.com/FRiCKLE/ngx_cache_purge/archive/${CACHE_VERSION}.tar.gz
CACHE_VERSION=2.3

#headers-more-nginx-module
#https://github.com/openresty/headers-more-nginx-module/archive/v{HMNM_NERSION}.tar.gz
HMNM_NERSION=0.33

#Directories
CURRENT_DIR=$(pwd)
OPENSSL_DIR=$(pwd)/openssl-${OPENSSL_VERSION}
CACHE_DIR=$(pwd)/ngx_cache_purge-${CACHE_VERSION}
HMNM_DIR=$(pwd)/headers-more-nginx-module-${HMNM_NERSION}
PAGESPEED_DIR=$(pwd)/incubator-pagespeed-ngx-${NPS_VERSION}-stable

#Save the nginx version
wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
tar -xvf nginx-${NGINX_VERSION}.tar.gz

#Save the openssl version
wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
tar -xvf openssl-${OPENSSL_VERSION}.tar.gz

#headers-more-nginx-module
wget https://github.com/openresty/headers-more-nginx-module/archive/v${HMNM_NERSION}.tar.gz
tar -xvf v${HMNM_NERSION}.tar.gz

#Cache Purge module
wget https://github.com/FRiCKLE/ngx_cache_purge/archive/${CACHE_VERSION}.tar.gz
tar -xvf ${CACHE_VERSION}.tar.gz

#Save ngx_pagespeed module
wget https://github.com/pagespeed/ngx_pagespeed/archive/v${NPS_VERSION}-stable.tar.gz
tar -xvf v${NPS_VERSION}-stable.tar.gz
cd incubator-pagespeed-ngx-${NPS_VERSION}-stable/
#Downloading psol
wget https://dl.google.com/dl/page-speed/psol/${NPS_VERSION}-x64.tar.gz
tar -xzvf ${NPS_VERSION}-x64.tar.gz

cd ..

#Entering inside the nginx folder
cd nginx-${NGINX_VERSION}

#Configuring
./configure  \
--prefix=/etc/nginx \
--sbin-path=/usr/sbin/nginx \
--modules-path=/usr/lib/nginx/modules \
--conf-path=/etc/nginx/nginx.conf \
--error-log-path=/var/log/nginx/error.log \
--http-log-path=/var/log/nginx/access.log \
--pid-path=/var/run/nginx.pid \
--lock-path=/var/run/nginx.lock \
--user=nginx \
--group=nginx \
--with-compat \
--with-file-aio \
--with-threads \
--with-http_addition_module \
--with-http_auth_request_module \
--with-http_dav_module \
--with-http_flv_module \
--with-http_gunzip_module \
--with-http_gzip_static_module \
--with-http_mp4_module \
--with-http_random_index_module \
--with-http_realip_module \
--with-http_secure_link_module \
--with-http_slice_module \
--with-http_ssl_module \
--with-http_stub_status_module \
--with-http_sub_module \
--with-http_v2_module \
--with-mail \
--with-mail_ssl_module \
--with-ipv6 \
--with-stream \
--with-stream_realip_module \
--with-stream_ssl_module \
--with-stream_ssl_preread_module \
--with-openssl=${OPENSSL_DIR} \
--add-module=${CACHE_DIR} \
--add-module=${HMNM_DIR} \
--add-module=${PAGESPEED_DIR} \
--with-cc-opt="-Wno-deprecated-declarations" \

# Compiling everything on 64 bits systems
KERNEL_BITS=64 make install

**Comment by oschaaf** [comment]
Usually there's a lot more in `/home/nginx/nginx-1.13.10/objs/autoconf.err `. Could you post the complete contents somewhere for inspection?

**Comment by oschaaf** [comment]
So the part that is relevant to ngx_pagespeed is:
```
checking for psol

/usr/bin/ld: cannot find -luuid
collect2: error: ld returned 1 exit status
```

You need to install some dependencies, see
https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source

e.g.:

```
sudo apt-get install build-essential zlib1g-dev libpcre3 libpcre3-dev unzip uuid-dev
```

**Comment by ooogooo** [comment]
thank you
