### ISSUE TITLE
PageSpeed Serf fetch failure rate extremely high; only 0 of 44 recent fetches fully successful

### ISSUE THREAD

**Issue by rickygm** [apache/incubator-pagespeed-ngx#1562]
Hi friends, I write because I need some help to refine pagespeed with nginx and https, I have a nginx as a reverse proxy of frontend and another nginx as a backend that has some apps in php7 and mariadb , For some time now I have been presenting the errors with pagespeed, I have searched for information about them and made adjustments to the settings, but I have not had success, I show you these errors:

 [error] 1322#22747: [ngx_pagespeed 1.13.35.2-0] PageSpeed Serf fetch failure rate extremely high; only 0 of 44 recent fetches fully successful; is fetching working?

I have tried according to the documentation https://www.modpagespeed.com/doc/https_support , but I can not solve the problem, I show them the configuration:

listen 443 ssl http2;
    server_name  myapp.domain.com
    pagespeed on;
    pagespeed FetchHttps enable;
    pagespeed FileCachePath /var/ngx_pagespeed_cache;
    pagespeed EnableFilters rewrite_css;
    pagespeed EnableFilters fallback_rewrite_css_urls;
    pagespeed EnableFilters combine_css;
    location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" { add_header "" ""; }
    location ~ "^/ngx_pagespeed_static/" { }
    location ~ "^/ngx_pagespeed_beacon" { }
    pagespeed LoadFromFile "https://www.domain.com/" "/var/www/webapp/";
    pagespeed LoadFromFileRuleMatch disallow .*;
    pagespeed LoadFromFileRuleMatch allow \.(ico|pdf|swf|eot|woff|ttf|otf|css|js|jpeg|jpg|png|gif|svg|svgz|mpg|mpeg|mp3|m4a|m4v|mp4|ogg|wmv|mov|mng|3gpp|3gp|webp|webm|flv|avi|asx|asf)
(\?.*)?$;

any help?

**Comment by Lofesa** [comment]
Hi
pagespeed LoadFromFileRuleMatch disallow .*; is the rigth statement to disallow all files.
And I can´t see the statement to set the certificates files and directory:

pagespeed SslCertDirectory directory;
pagespeed SslCertFile file;

These file and directory are not the ssl certificates of your site but the certificates for a client. For eample in a centos 7 distro:
pagespeed SslCertDirectory /etc/pki/tls/certs;
pagespeed SslCertFile /etc/pki/tls/cert.pem;

**Comment by rickygm** [comment]
Hi Lofesa , I'm using letsencrypt , and I'm not sure if it's the right way, another doubt I do not know when that specific error occurs, I'm accessing my applications and I do not see the error at the moment.

I show you how to leave the current configuration:
listen 443 ssl http2;
server_name myapp.domain.com
pagespeed on;
pagespeed FetchHttps enable;
pagespeed FileCachePath /var/ngx_pagespeed_cache;
pagespeed EnableFilters rewrite_css;
pagespeed EnableFilters fallback_rewrite_css_urls;
pagespeed EnableFilters combine_css;
location ~ ".pagespeed.([a-z].)?[a-z]{2}.[^.]{10}.[^.]+" { add_header "" ""; }
location ~ "^/ngx_pagespeed_static/" { }
location ~ "^/ngx_pagespeed_beacon" { }
pagespeed LoadFromFile "https://www.domain.com/" "/var/www/webapp/";
pagespeed LoadFromFileRuleMatch disallow .;
pagespeed LoadFromFileRuleMatch allow .(ico|pdf|swf|eot|woff|ttf|otf|css|js|jpeg|jpg|png|gif|svg|svgz|mpg|mpeg|mp3|m4a|m4v|mp4|ogg|wmv|mov|mng|3gpp|3gp|webp|webm|flv|avi|asx|asf)
(?.)?$;
pagespeed SslCertDirectory /etc/letsencrypt/live/domain.com;
pagespeed SslCertFile /etc/letsencrypt/live/domain.com/cert.pem;

thanks for all help!

**Comment by chaihongjun** [comment]
@rickygm  your setting is correct

pagespeed SslCertDirectory /etc/letsencrypt/live/domain.com;
pagespeed SslCertFile /etc/letsencrypt/live/domain.com/cert.pem;

**Comment by oschaaf** [comment]
@rickygm for setting up https fetching, reading https://www.modpagespeed.com/doc/https_support#configuring_ssl_certificates closely may be helpful.
(the configuration you have mentions domain.com, which makes me think it's not right).

Urls matching the LoadFromFileXXX configuration do not need the https fetching to work though.
So if you still observe https fetching errors, you need to double check that configuration to see if it actually matches the target urls -- perhaps through a regex validator.

Closing this issue, but feel free to re-open if there is still a problem.
