### ISSUE TITLE
How to disable POST ngx_pagespeed_beacon?

### ISSUE THREAD

**Issue by extensionsapp** [apache/incubator-pagespeed-ngx#1565]
Hello.

```
46.37.47.190 - - [23/May/2018:23:07:23 +0300] "POST /ngx_pagespeed_beacon?url=https%3A%2F%2Fhello.cc%2Fhd%2Fmontana.asp HTTP/1.1" 204 0 "https://hello.cc/hd/montana.asp" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "-"
```

I add:
```
    pagespeed ReportUnloadTime off;
    pagespeed Statistics off;
    pagespeed StatisticsLogging off;
```

How to disable POST ngx_pagespeed_beacon? I not use statistics.

**Comment by oschaaf** [comment]
See https://www.modpagespeed.com/doc/faq#control_beacons

**Comment by ozdemirburak** [comment]
I tried both configurations, but none of them works for nginx. @oschaaf, I'd be grateful if you can provide a better solution for nginx.

```nginx
pagespeed CriticalImagesBeaconEnabled false;
pagespeed DisableFilters lazyload_images;
pagespeed DisableFilters inline_images;
pagespeed DisableFilters inline_preview_images;
pagespeed DisableFilters rewrite_images;

# location ~ "^/ngx_pagespeed_beacon$" { }
location ~ "^/ngx_pagespeed_beacon$" { deny all; }
```

**Comment by Lofesa** [comment]
> location ~ "^/ngx_pagespeed_beacon$" { deny all; }

Where have you set this directive?
This don´t prevent the POST request, but returns a 403 forbiden code and the POST data is not processed.

To don´t have any beacon you need to disable all image filters (or near all image filters)
Why don´t try to use some like `pagespeed RewriteLevel OptimizeForBandwidth `?

**Comment by ozdemirburak** [comment]
Thanks for your reply @Lofesa.

> Where have you set this directive?

I included my pagespeed configuration under a server block.

I tried that location directive because the document linked above mentions disabling image rewriting filters or directly denying the requests. And here is the reason why I disabled these filters specifically. Here is the passage from [another documentation page](https://www.modpagespeed.com/doc/config_filters):

> The lazyload_images, inline_preview_images, and inline_images filters, use a beacon to collect information about the rewritten page so as to optimize the rewriting process. The beacon is a POST request sent back by JavaScript inserted into the page by the filter. The use of this beacon is on by default but it can be disabled using:

If I need to disable nearly all image filters, which image filters my configuration is missing? 
 
On the other hand, I'll try `OptimizeForBandwidth`.

**Comment by Lofesa** [comment]
I don´t know all the image filter that uses beacon, but for sure  resize_rendered_image_dimensions is one of these image filters, but other filters, css related, uses it too (the prioritize_critical_css).
Beacons returns back to server some info, like if the image is in the viewport, what are the rendered dimensions, what is the critical css to load and what css to defer....So disabling beacons most of the image filters don´t work well nor the prioritize_css_critical.

By default, pagespeed works with a "core" rewrite level. This level enables a bunch of filters.
An alternative is to use the `pagespeed RewriteLevel OptimizeForBandwidth` this rewrite level do some optimization work and can´t rewrite the html code at all.
Other is use of `pagespeed RewriteLevel PassThrough` this one only enables the filter you explicitly enable.
See: https://www.modpagespeed.com/doc/config_filters#level

**Comment by ozdemirburak** [comment]
Thanks, @Lofesa. Your answers are really helpful for anyone facing this issue. For my case, I think [prioritize_critical_css](https://www.modpagespeed.com/doc/filter-prioritize-critical-css) was the one that caused this behavior for me.
