### ISSUE TITLE
PageSpeed could not optimize (Proxy_pass) if response returned 200

### ISSUE THREAD

**Issue by redbox-cdn** [apache/incubator-pagespeed-ngx#1570]
Hi.
I feel something strange is going on pagespeed optimize action.

Situation: 
Client -- Nginx(pagespeed and Proxy_pass) -- Origin Web server

Client send request into Pagespeed including "if modify since" header,
Pagespeed does not optimize if origin Web server return 304. 

So, I added the `proxy_set_header If-Modified-Since "";` proxy_pass directive.
After that Origin Web server response is 200 but Pagespeed could not optimize.

### nginx Debug message

`[ngx_pagespeed 1.13.35.1-0] Could not rewrite resource in-place because URL is not in cache: http://test.com/test/test.css`

### TEST request

`curl -svko /dev/null 'http://1.1.1.1/test/test.css' -H 'Host: test.com' -H 'X-forwarded-proto: https' -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'If-Modified-Since: Mon, 04 Jun 2018 09:00:52 GMT'
`

### Origin Server response

```
< HTTP/1.1 200 OK
< Date: Fri, 08 Jun 2018 02:48:01 GMT
< Content-Type: text/css
< Content-Length: 198
< Connection: keep-alive
< Vary: Accept-Encoding
< Last-Modified: Mon, 04 Jun 2018 09:00:52 GMT
< Accept-Ranges: bytes
< Cache-Control: max-age=3024000
< Expires: Fri, 13 Jul 2018 02:48:01 GMT
< Vary: Accept-Encoding
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Content-Type
< Access-Control-Allow-Credentials: true
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```

### Nginx conf
```
server {

    listen 80;

    location / {

        proxy_set_header If-Modified-Since ""; ## ADD

        proxy_read_timeout 3600;
        more_clear_headers Server: ;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        resolver_timeout 300s;
        resolver 8.8.8.8 8.8.4.4 valid=300s;
        proxy_pass  $http_backend_schema://test.com;
        proxy_set_header Host                   $host;
        proxy_redirect     off;
        }

    pagespeed on;

    location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
        add_header "" "";
    }
    ##Cache Settings

    pagespeed FileCacheSizeKb            10000;
    pagespeed FileCacheCleanIntervalMs   5000;
    pagespeed FileCacheInodeLimit        100;
    pagespeed FileCachePath /home/cache
    pagespeed ImplicitCacheTtlMs 1;
    pagespeed ModifyCachingHeaders off;
    pagespeed EnableFilters in_place_optimize_for_browser;
    pagespeed HttpCacheCompressionLevel 0;
    pagespeed CriticalImagesBeaconEnabled false;
    pagespeed InPlaceResourceOptimization on;
    pagespeed PreserveUrlRelativity on;
    pagespeed JsPreserveURLs on;
    pagespeed ImagePreserveURLs on;
    pagespeed CssPreserveURLs on;
    pagespeed DownstreamCachePurgeLocationPrefix "http://localhost/purge";
    pagespeed DownstreamCachePurgeMethod "POST";
    pagespeed DownstreamCacheRebeaconingKey "test";
    pagespeed CustomFetchHeader X-Forwarded-proto $http_x_forwarded_proto;
    pagespeed RateLimitBackgroundFetches off;

    pagespeed RewriteLevel PassThrough;
    pagespeed EnableFilters add_head,rewrite_css,flatten_css_imports,fallback_rewrite_css_urls,rewrite_javascript,remove_comments,insert_dns_prefetch,in_place_optimize_for_browser;

    #Purge request
    pagespeed PurgeMethod PURGE;
    pagespeed EnableCachePurge on;
}
```

Does anyone know something good solution?

**Comment by jmarantz** [comment]
Could you try fetching the CSS file three times?

On the first request, PageSpeed will collect the resource as it streams through the system, saving it in its HTTP cache.

On the second request, a rewrite of the CSS file will be initiated in a background thread.  This will probably take a few milliseconds, or more if there are images referenced in the CSS file and the need to be optimized.

On the third request -- if enough time has elapsed since the second request, the CSS file (and the referenced images) should all be optimized.

**Comment by jmarantz** [comment]
please re-open if questions remain.

**Comment by redbox-cdn** [comment]
I tried more then 3 requests but it does not optimize.

It seems that Pagespeed could not cached.because everytime request log on the origin Web server can be confirmed. 

But "If modify since header" does not set into request, Pagespeed is normally Work.

**Comment by jmarantz** [comment]
To clarify, do I have this right?

a) if you remove the if-modify-since header, optimization works, at least after 3 requests?
b) If you include the if-modify-since header, optimization fails

Is that right?

**Comment by redbox-cdn** [comment]
Hi 

> a) if you remove the if-modify-since header, optimization works, at least after 3 requests?
no, it does not optimized least after 3 request.

> b) If you include the if-modify-since header, optimization fails
yes

This problem is occurred first request if Pagespeed has not contents cached. 

I tried below situation.

Send the first request (not include the "If-modify-since" header ) 
*PageSpeed can be cached.

when send the second request  with "if modify since" header. 
Pagespeed returned optimized contents.

**Comment by jmarantz** [comment]
I think I wouldn't call this a bug.  PageSpeed can't optimize resources that are served by origin with a validator like if-modified-since.

You could argue that if you turn on the delivery of that header, PageSpeed should not optimize it. However, since PageSpeed already cached the version of the resource that had no validator, it has the right to use the second request to initiate the optimization, and the third request to serve the optimized content.

**Comment by redbox-cdn** [comment]
IMS header unset before Origin server request.(proxy) In addition, origin responsed 200.

The point is if request includ IMS header, even if I unset the IMS header, pagespeed clould  not optimize?

**Comment by oschaaf** [comment]
re: "I will try debug that set the proxy can be delete IMS request header in front of pagespeed" 

I think that would help.

**Comment by redbox-cdn** [comment]
Hi 
Just as expected, 
removed IMS header using varnish in front of pagespeed. the contents is optimized by pagespeed.

So, even if remove IMS header setting in the server directive of nginx and furthermore origin response is 200,
it seems Pagespeed decided request header faster than other directive.

But I think problem is not about priority. if origin response is 200, pagespeed should cache the contents.

this problem will occured when expired cached content of the pagespeed and 
included IMS header of client request .

**Comment by oschaaf** [comment]
Can you post the debug level logs of nginx for a couple of these css-requests in sequence?

**Comment by redbox-cdn** [comment]
Hi 
here is the debug log. I tried 4 requests but it does not cached.
[debug.log](https://github.com/apache/incubator-pagespeed-ngx/files/2083887/debug.log)

**Comment by redbox-cdn** [comment]
Hi otto.
Sorry I mistake attached debug logs.
 
I forgot set the `proxy_set_header If-Modified-Since ""; ## ADD` 

New debug logs is attached again.
[debug-2.log](https://github.com/apache/incubator-pagespeed-ngx/files/2084064/debug-2.log)

And Last-Modified header is added by origin server.

in Addition, Request is CURL command.

`curl -svko /dev/null 'http://1.1.1.1/test/test.css' -H 'Host: test.com' -H 'X-forwarded-proto: https' -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'If-Modified-Since: Mon, 04 Jun 2018 09:00:52 GMT'
`

**Comment by oschaaf** [comment]
So `Last-Modified` is added by the origin. What I still don't get is how the `Last-Modified` header gets put on the wire after flowing through ngx_pagespeed. 

It looks like it ought to be stripped by pagespeed. Diff between responses with pagespeed off and on:
```
oschaaf@HP-Z620:~$ diff <(curl -sI https://www.ngxpagespeed.com/images/Puzzle.jpg?PageSpeed=off | sort) <(curl -sI https://www.ngxpagespeed.com/images/Puzzle.jpg | sort)
2a3
> Cache-Control: max-age=239
4c5
< Content-Length: 241260
---
> Content-Length: 98051
7c8,9
< ETag: "5a030687-3ae6c"
---
> ETag: W/"PSA-aj-YsUBdV-i_6"
> Expires: Fri, 08 Jun 2018 13:51:49 GMT
9d10
< Last-Modified: Wed, 08 Nov 2017 13:28:39 GMT
11a13
> X-Original-Content-Length: 241260
```

As you can see Last-Modified only exists in the non-pagespeed version.

**Comment by jmarantz** [comment]
I think PageSpeed adds Last-Modified.

**Comment by oschaaf** [comment]
So... in IPRO:

https://www.modpagespeed.com/network-loading.png?random=foo

first request has it:
```
HTTP/1.1 200 OK
Date: Fri, 08 Jun 2018 14:00:59 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 11 Jan 2018 21:51:58 GMT
Accept-Ranges: bytes
Content-Length: 152825
Cache-control: public, max-age=600, s-maxage=10
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: image/png
```

second request, it's gone:
```
HTTP/1.1 200 OK
Date: Fri, 08 Jun 2018 14:01:12 GMT
Server: Apache/2.4.18 (Ubuntu)
Content-Length: 152825
Last-Modified: Thu, 11 Jan 2018 21:51:58 GMT
Accept-Ranges: bytes
Etag: W/"PSA-q7JIszBKQS"
Cache-Control: public, max-age=600, s-maxage=10
X-Content-Type-Options: nosniff
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: image/png
```

**Comment by oschaaf** [comment]
Sorry, must get my eyes check (again) :-)

Second request, it's still there, but the third request it is gone:

```
HTTP/1.1 200 OK
Date: Fri, 08 Jun 2018 14:02:07 GMT
Server: Apache/2.4.18 (Ubuntu)
Content-Length: 124338
Accept-Ranges: bytes
X-Original-Content-Length: 152825
Etag: W/"PSA-aj-eddLATvDaI"
Expires: Fri, 08 Jun 2018 14:10:59 GMT
Cache-Control: max-age=531, public
X-Content-Type-Options: nosniff
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: image/png
```

**Comment by redbox-cdn** [comment]
Hi all  thank you for checking !

I am not sure, this issue is related to `Last-Modified` header add by Origin server?

the pagespeed removed of Last-Modified header after optimized ?(third request)
If so, separate matter, client can't use browser cache.

**Comment by oschaaf** [comment]
In the fully optimized response `Last-Modified` is gone but there is an `Etag` validator. 

What I'm saying is that as `Last-Modified` will be omitted from optimized responses, the number of requests that actually have `If-Modified-Since` will gradually go down to 0. 

So I think that  while (synthentic) requests with `If-Modified-Since` may not be optimized in your proxy set up, it's not a (persistent) real-world issue, because nobody will end up sending it.

**Comment by redbox-cdn** [comment]
Hi otto
Your explanation became clear to me!
As you said If ETAG is exist, browser cache will enabled So,  the number of requests that actually have `If-Modified Since`  is gradually go down.
