### ISSUE TITLE
404 on HTTPs

### ISSUE THREAD

**Issue by attinderdhillon** [apache/incubator-pagespeed-ngx#1571]
It works fine on http but with https enabled all assets processed by pagespeed are 404.
This is a test setup on nginx, same website with letscrypt ssl works fine on apache modspeed.

Tried latest stable and release, 
pagespeed installed as dynamic module.

This is my pagespeed conf, kindly suggest a solution.

` pagespeed on;
 pagespeed HonorCsp on;

 pagespeed RespectXForwardedProto on;

 #Same issue with these enabled and loadfrom file disabled.
 #pagespeed SslCertDirectory /etc/pki/tls/certs;
 #pagespeed SslCertFile /etc/pki/tls/cert.pem;

 pagespeed LoadFromFile "https://test.site.com" "/home/test/public_html/";

 pagespeed RewriteLevel CoreFilters;

 pagespeed XHeaderValue "Powered By ngx_pagespeed";
 pagespeed FileCachePath /var/cache/nginx/;

 location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
       add_header "" "";
 }
 location ~ "^/pagespeed_static/" { }
 location ~ "^/ngx_pagespeed_beacon$" { }`

**Comment by oschaaf** [comment]
Either LoadFromFile is not matching with the incoming urls, or it does match but the module isn't able to get direct access the mapped static files. You have `pagespeed RespectXForwardedProto on;`, which makes me think chances are the incoming urls do not match. Presumably there is a reverse proxy running in front that terminates https. What happens when you test the server directly?

**Comment by attinderdhillon** [comment]
I was just testing "RespectXFor.." , didn't help.
No proxy, just nginx/php-fpm.

Pagespeed cache is getting populated.
Ex. there is a file under ../v3/site/https,3A/..  "xfavicon-16x16.png.pagespeed.ic.JI0K0aTlw4.webp"  
but it is 404 when directly called in browser , https://site.com/xfavicon-16x16.png.pagespeed.ic.JI0K0aTlw4.webp

Directly every thing works,  https://site.com/favicon-16x16.png is accessible.

**Comment by attinderdhillon** [comment]
I reinstalled & everything working great now.
Must be a config issue somewhere.
