### ISSUE TITLE
goog.crypt.base64 not working after pagespeed is enabled

### ISSUE THREAD

**Issue by NisariAIT** [apache/incubator-pagespeed-ngx#1578]
I was using goog.crypt.base64 in my application running Ubuntu server 16.04 with nginx. I recently installed pagespeed 1.13.35.2-0. After this, one of the features that were using goog.crypt.base64 stopped working and the error is as follows:
![image](https://user-images.githubusercontent.com/36888737/42560575-9618af64-8514-11e8-9d61-9162f9c2dd67.png)
When pagespeed was turned off, the feature seems to work well. Could someone tell me what causes this issue and how it can be fixed?

**Note: this error is received only from second page load. If pagespeed cache is cleared, it works for the first time the page is loaded**

**Comment by oschaaf** [comment]
Can you try turning off combine_javascript?

**Comment by NisariAIT** [comment]
I added this: 
`pagespeed DisableFilters combine_javascript; `
after ```
pagespeed on;
            pagespeed HonorCsp on;
```
But I have the same error still. I am also getting this error in one other place:
![image](https://user-images.githubusercontent.com/36888737/42569195-5c659962-852d-11e8-9950-f9f5fcb7791c.png)

**Comment by NisariAIT** [comment]
No @Lofesa. I have not enabled defer javascript.

**Comment by jmarantz** [comment]
How are you integrating the closure-library? Are you compiling
<https://developers.google.com/closure/compiler/> your JavaScript with the
closure library? Usually goog.require doesn't run when you load the page;
it is handled at the compilation step. There are various ad-hoc ways of
getting around this so you can load your closure-library dependencies
without a compilation step. I use them myself, but only for debugging
JavaScript.

It's possible that PageSpeed's use of closure-compiled libraries (e.g. for
detecting above-the-fold images) is interfering with some ad-hoc mechanism
you've picked up somewhere. Or maybe PageSpeed's renaming of JavaScript
files is getting in the way of that ad-hoc mechanism.

It should be easy to get to the bottom of this if you give more detail
about how you are using the closure library.

**Comment by NisariAIT** [comment]
@jmarantz, I am not compiling javascript using closure compiler. I have not installed a compiler/builder(https://developers.google.com/closure/compiler/).

**Comment by NisariAIT** [comment]
@jmarantz, How can I check if the script is using a compiler? The script is as below:
goog.require('goog.crypt.base64');

**Comment by jmarantz** [comment]
The compile can't be run from your web page. It's run by installing it on
your workstation and incorporating it into a process for compiling your
JavaScript source code into new JavaScript that is suitable for delivery on
the web.

AFAIK the libraries you are using are intended only for use with the
closure compiler. So if you have not incorporated I'm very curious to know
how you're loading the JavaScript.  E.g. are you hosting the closure
compiler source JS yourself?

**Comment by NisariAIT** [comment]
@jmarantz, I was not the one who compiled the JS closure libraries. I was given a set of js files that can be used in the web application directly(which I think must be because it was compiled with a closure compiler?).

**Comment by jmarantz** [comment]
Can you paste the HTML that lists the JavaScript you have? Are you hosting
the JS yourself?

**Comment by NisariAIT** [comment]
Yes @jmarantz, the script files are hosted by us. The deps.js file is not being called directly in the application. When goog.require is used, the deps.js file is called and this file uses the other JS files within the library to complete the process. 
I have resolved it by using the following directive: pagespeed Disallow "*js/MiscJS/*".
