### ISSUE TITLE
Cannot combine xxx: combined url too long

### ISSUE THREAD

**Issue by kylephp** [apache/incubator-pagespeed-ngx#1586]
Hi,
I am using Nginx 1.15.2 compiled with mod_pagespeed 1.13.35.2 but it seems not stable. JavaScript files sometimes could be combined but sometimes not. I checked the logs and here are some ngx_pagespeed complain:
`2018/08/15 05:06:29 [info] 30#38: [ngx_pagespeed 1.13.35.2-0] Cannot combine http://localhost/portal/modules/mod_pegasus_portal/tmpl/lockscreen/lockScreen.js?v=120: combined url too long.`
I have tried to increase the `MaxSegmentLength` setting but it was the same problem
I have attached my settings. Can anybody help me?
![settings](https://user-images.githubusercontent.com/7766055/44132798-0f66f1dc-a086-11e8-88ca-350fa3d6f920.png)

**Comment by kylephp** [comment]
@oschaaf Sorry to tag you in but I don't know who I should count on

**Comment by oschaaf** [comment]
The logged message isn't a complaint, but rather an informational message. 
If you want to permit the combiners to compose larger urls, you can tweak `MaxSegmentLength` and `MaxUrlSize`  (undocumented).  Before doing that, please see the warning at https://www.modpagespeed.com/doc/restricting_urls#segment_length

**Comment by kylephp** [comment]
@oschaaf thanks for replying. It was not about the logged message, I can see it's working unstably: sometimes the JS files could be combined partially (acceptable since we have some big files and served their own) but when I hit f5 to refresh the page it loaded every single files.
P/S: my site is SPA so it contains a lot of JS files, I use mod_pagespeed to reduce the page load time

**Comment by kylephp** [comment]
![screencast](https://user-images.githubusercontent.com/7766055/44380329-ded23280-a534-11e8-82fb-6a4474112583.gif)
