### ISSUE TITLE
Pagespeed conflicts with Nginx Headers module

### ISSUE THREAD

**Issue by NisariAIT** [apache/incubator-pagespeed-ngx#1596]
I have compiled pagespeed(1.13.35) with nginx(1.15.1). In the responses from the web server, the name of the app server(in the Server header) is displayed. To avoid the name getting disclosed, I have compiled an additional module with nginx called the headers-more module. This module works fine when pagespeed is turned OFF. However, when we turn ON pagespeed, the name of the server starts getting displayed in the response header in spite of the additional module.

Is it possible to prevent pagespeed from overriding the configurations of the headers more module?

**Comment by oschaaf** [comment]
This is a known issue, being tracked elsewhere. See https://groups.google.com/forum/m/#!topic/ngx-pagespeed-discuss/PmKakhMImEQ and specifically POSITION_AUX for a potential resolution. (I'm not sure if that flag still works as intended)

**Comment by NisariAIT** [comment]
@oschaaf , Compiling nginx with pagespeed as a dynamic module and using the Position_aux flag did not remove the header. Can we expect a fix for this issue sometime?
