### ISSUE TITLE
UrlValuedAttribute don´t work w/ data-srcset elements

### ISSUE THREAD

**Issue by Lofesa** [apache/incubator-pagespeed-ngx#1608]
Hi
I have a wordpress plugin to lazyload images as far that the lazyload filter load images at onload event, no matter if LazyloadImagesAfterOnload is set to off.
I use

pagespeed UrlValuedAttribute img data-srcset image;

but this get not image optimized nor url rewrited, only some like that  `data-src="url-to-image.jpg%20500w,url-to-image.jpg%20150w.....`
when pagespeed UrlValuedAttribute img data-srcset image; is not set, url images in data-srcset are not touched, but in headers they have this content-type: image/webp

This filter
pagespeed UrlValuedAttribute img data-src image;

do the work rigth. Is a single image statement, the image get optimized, converted to webp in chrome.....

**Comment by Lofesa** [comment]
ping @oschaaf

**Comment by oschaaf** [comment]
hi @Lofesa; I am not 100% sure I follow; are you pointing out a bug, or perhaps suggesting an improvement? Could you perhaps add a more elaborate example? That may help me understand you better.

**Comment by oschaaf** [comment]
Oh wait, I missed https://github.com/apache/incubator-pagespeed-mod/issues/1849 referenced this, which has a title that consicely describes what you mean here.

**Comment by Lofesa** [comment]
Close this by [#1899](https://github.com/apache/incubator-pagespeed-mod/pull/1899)
