### ISSUE TITLE
Dependencies installed, psol not found

### ISSUE THREAD

**Issue by JediKnightChan** [apache/incubator-pagespeed-ngx#1611]
Executed:
apt-get install build-essential zlib1g-dev libpcre3 libpcre3-dev

cd /temp
wget github.com/pagespeed/ngx_pagespeed/archive/v1.7.30.1-beta.zip
unzip v1.7.30.1-beta.zip
cd ngx_pagespeed-1.7.30.1-beta
wget dl.google.com/dl/page-speed/psol/1.7.30.1.tar.gz
tar -xzvf 1.7.30.1.tar.gz
wget nginx.org/download/nginx-1.4.5.tar.gz
tar -xvzf nginx-1.4.5.tar.gz
cd nginx-1.4.5/
./configure --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --sbin-path=/usr/sbin/nginx --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/body --http-proxy-temp-path=/var/lib/nginx/proxy --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --http-scgi-temp-path=/var/lib/nginx/scgi --prefix=/var/lib/nginx --with-http_stub_status_module --with-http_flv_module --with-http_ssl_module --with-http_dav_module --with-http_sub_module --with-http_realip_module --with-http_gzip_static_module --with-http_secure_link_module --with-ipv6 --with-debug --add-module=/temp/ngx_pagespeed-1.7.30.1-beta

Got:

checking for OS
 + Linux 4.4.0-139-generic x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
checking for gcc -pipe switch ... found
checking for gcc builtin atomic operations ... found
checking for C99 variadic macros ... found
checking for gcc variadic macros ... found
checking for unistd.h ... found
checking for inttypes.h ... found
checking for limits.h ... found
checking for sys/filio.h ... not found
checking for sys/param.h ... found
checking for sys/mount.h ... found
checking for sys/statvfs.h ... found
checking for crypt.h ... found
checking for Linux specific features
checking for epoll ... found
checking for sendfile() ... found
checking for sendfile64() ... found
checking for sys/prctl.h ... found
checking for prctl(PR_SET_DUMPABLE) ... found
checking for sched_setaffinity() ... found
checking for crypt_r() ... found
checking for sys/vfs.h ... found
checking for nobody group ... not found
checking for nogroup group ... found
checking for poll() ... found
checking for /dev/poll ... not found
checking for kqueue ... not found
checking for crypt() ... not found
checking for crypt() in libcrypt ... found
checking for F_READAHEAD ... not found
checking for posix_fadvise() ... found
checking for O_DIRECT ... found
checking for F_NOCACHE ... not found
checking for directio() ... not found
checking for statfs() ... found
checking for statvfs() ... found
checking for dlopen() ... not found
checking for dlopen() in libdl ... found
checking for sched_yield() ... found
checking for SO_SETFIB ... not found
checking for SO_ACCEPTFILTER ... not found
checking for TCP_DEFER_ACCEPT ... found
checking for TCP_KEEPIDLE, TCP_KEEPINTVL, TCP_KEEPCNT ... found
checking for TCP_INFO ... found
checking for accept4() ... found
checking for int size ... 4 bytes
checking for long size ... 8 bytes
checking for long long size ... 8 bytes
checking for void * size ... 8 bytes
checking for uint64_t ... found
checking for sig_atomic_t ... found
checking for sig_atomic_t size ... 4 bytes
checking for socklen_t ... found
checking for in_addr_t ... found
checking for in_port_t ... found
checking for rlim_t ... found
checking for uintptr_t ... uintptr_t found
checking for system byte ordering ... little endian
checking for size_t size ... 8 bytes
checking for off_t size ... 8 bytes
checking for time_t size ... 8 bytes
checking for AF_INET6 ... found
checking for setproctitle() ... not found
checking for pread() ... found
checking for pwrite() ... found
checking for sys_nerr ... found
checking for localtime_r() ... found
checking for posix_memalign() ... found
checking for memalign() ... found
checking for mmap(MAP_ANON|MAP_SHARED) ... found
checking for mmap("/dev/zero", MAP_SHARED) ... found
checking for System V shared memory ... found
checking for POSIX semaphores ... not found
checking for POSIX semaphores in libpthread ... found
checking for struct msghdr.msg_control ... found
checking for ioctl(FIONBIO) ... found
checking for struct tm.tm_gmtoff ... found
checking for struct dirent.d_namlen ... not found
checking for struct dirent.d_type ... found
checking for sysconf(_SC_NPROCESSORS_ONLN) ... found
checking for openat(), fstatat() ... found
checking for getaddrinfo() ... found
configuring additional modules
adding module in /temp/ngx_pagespeed
mod_pagespeed_dir=/temp/ngx_pagespeed/psol/include
build_from_source=false
checking for psol ... not found
./configure: error: module ngx_pagespeed requires the pagespeed optimization library.
Look in /temp/ngx_pagespeed/nginx-1.4.5/objs/autoconf.err for more details.

Autoconf:
`

----------------------------------------
checking for C compiler

----------------------------------------
checking for gcc -pipe switch

----------------------------------------
checking for gcc builtin atomic operations

----------------------------------------
checking for C99 variadic macros

----------------------------------------
checking for gcc variadic macros

----------------------------------------
checking for unistd.h

----------------------------------------
checking for inttypes.h

----------------------------------------
checking for limits.h

----------------------------------------
checking for sys/filio.h

objs/autotest.c:3:23: fatal error: sys/filio.h: No such file or directory
compilation terminated.
----------

#include <sys/filio.h>

int main() {
    return 0;
}

----------
cc -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for sys/param.h

----------------------------------------
checking for sys/mount.h

----------------------------------------
checking for sys/statvfs.h

----------------------------------------
checking for crypt.h

----------------------------------------
checking for epoll

----------------------------------------
checking for sendfile()

----------------------------------------
checking for sendfile64()

----------------------------------------
checking for sys/prctl.h

----------------------------------------
checking for prctl(PR_SET_DUMPABLE)

----------------------------------------
checking for sched_setaffinity()

----------------------------------------
checking for crypt_r()

----------------------------------------
checking for sys/vfs.h

----------------------------------------
checking for poll()

----------------------------------------
checking for /dev/poll

objs/autotest.c:4:25: fatal error: sys/devpoll.h: No such file or directory
compilation terminated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/devpoll.h>

int main() {
    int  n, dp; struct dvpoll  dvp;
                  dp = 0;
                  dvp.dp_fds = NULL;
                  dvp.dp_nfds = 0;
                  dvp.dp_timeout = 0;
                  n = ioctl(dp, DP_POLL, &dvp);
                  if (n == -1) return 1;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for kqueue

objs/autotest.c:4:23: fatal error: sys/event.h: No such file or directory
compilation terminated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/event.h>

int main() {
    int kq; kq = kqueue();
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for crypt()

/tmp/cc0sqcPK.o: In function `main':
autotest.c:(.text+0xf): undefined reference to `crypt'
collect2: error: ld returned 1 exit status
----------

#include <sys/types.h>
#include <unistd.h>

int main() {
    crypt("test", "salt");;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for crypt() in libcrypt

----------------------------------------
checking for F_READAHEAD

objs/autotest.c: In function 'main':
objs/autotest.c:7:14: error: 'F_READAHEAD' undeclared (first use in this function)
     fcntl(0, F_READAHEAD, 1);;
              ^
objs/autotest.c:7:14: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <fcntl.h>

int main() {
    fcntl(0, F_READAHEAD, 1);;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for posix_fadvise()

----------------------------------------
checking for O_DIRECT

----------------------------------------
checking for F_NOCACHE

objs/autotest.c: In function 'main':
objs/autotest.c:7:14: error: 'F_NOCACHE' undeclared (first use in this function)
     fcntl(0, F_NOCACHE, 1);;
              ^
objs/autotest.c:7:14: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <fcntl.h>

int main() {
    fcntl(0, F_NOCACHE, 1);;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for directio()

objs/autotest.c: In function 'main':
objs/autotest.c:8:5: warning: implicit declaration of function 'directio' [-Wimplicit-function-declaration]
     directio(0, DIRECTIO_ON);;
     ^
objs/autotest.c:8:17: error: 'DIRECTIO_ON' undeclared (first use in this function)
     directio(0, DIRECTIO_ON);;
                 ^
objs/autotest.c:8:17: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/types.h>
                  #include <sys/fcntl.h>

int main() {
    directio(0, DIRECTIO_ON);;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for statfs()

----------------------------------------
checking for statvfs()

----------------------------------------
checking for dlopen()

/tmp/cc2j85An.o: In function `main':
autotest.c:(.text+0xf): undefined reference to `dlopen'
collect2: error: ld returned 1 exit status
----------

#include <sys/types.h>
#include <unistd.h>
#include <dlfcn.h>

int main() {
    dlopen(NULL, 0);
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for dlopen() in libdl

----------------------------------------
checking for sched_yield()

----------------------------------------
checking for SO_SETFIB

objs/autotest.c: In function 'main':
objs/autotest.c:7:31: error: 'SO_SETFIB' undeclared (first use in this function)
     setsockopt(0, SOL_SOCKET, SO_SETFIB, NULL, 4);
                               ^
objs/autotest.c:7:31: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>

int main() {
    setsockopt(0, SOL_SOCKET, SO_SETFIB, NULL, 4);
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for SO_ACCEPTFILTER

objs/autotest.c: In function 'main':
objs/autotest.c:7:31: error: 'SO_ACCEPTFILTER' undeclared (first use in this function)
     setsockopt(0, SOL_SOCKET, SO_ACCEPTFILTER, NULL, 0);
                               ^
objs/autotest.c:7:31: note: each undeclared identifier is reported only once for each function it appears in
----------

#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>

int main() {
    setsockopt(0, SOL_SOCKET, SO_ACCEPTFILTER, NULL, 0);
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for TCP_DEFER_ACCEPT

----------------------------------------
checking for TCP_KEEPIDLE, TCP_KEEPINTVL, TCP_KEEPCNT

----------------------------------------
checking for TCP_INFO

----------------------------------------
checking for accept4()

----------------------------------------
checking for int size

----------------------------------------
checking for long size

----------------------------------------
checking for long long size

----------------------------------------
checking for void * size

----------------------------------------
checking for uint64_t

----------------------------------------
checking for sig_atomic_t

----------------------------------------
checking for sig_atomic_t size

----------------------------------------
checking for socklen_t

----------------------------------------
checking for in_addr_t

----------------------------------------
checking for in_port_t

----------------------------------------
checking for rlim_t

checking for uintptr_t

checking for system byte ordering

----------------------------------------
checking for size_t size

----------------------------------------
checking for off_t size

----------------------------------------
checking for time_t size

----------------------------------------
checking for AF_INET6

----------------------------------------
checking for setproctitle()

objs/autotest.c: In function 'main':
objs/autotest.c:7:5: warning: implicit declaration of function 'setproctitle' [-Wimplicit-function-declaration]
     setproctitle("test");;
     ^
/tmp/ccEhTTDn.o: In function `main':
autotest.c:(.text+0xf): undefined reference to `setproctitle'
collect2: error: ld returned 1 exit status
----------

#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>

int main() {
    setproctitle("test");;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for pread()

----------------------------------------
checking for pwrite()

----------------------------------------
checking for sys_nerr

/tmp/ccdm4Uby.o: In function `main':
autotest.c:(.text+0x6): warning: `sys_nerr' is deprecated; use `strerror' or `strerror_r' instead
135
----------------------------------------
checking for localtime_r()

----------------------------------------
checking for posix_memalign()

----------------------------------------
checking for memalign()

----------------------------------------
checking for mmap(MAP_ANON|MAP_SHARED)

----------------------------------------
checking for mmap("/dev/zero", MAP_SHARED)

----------------------------------------
checking for System V shared memory

----------------------------------------
checking for POSIX semaphores

/tmp/cc19wDQb.o: In function `main':
autotest.c:(.text+0x29): undefined reference to `sem_init'
autotest.c:(.text+0x41): undefined reference to `sem_destroy'
collect2: error: ld returned 1 exit status
----------

#include <sys/types.h>
#include <unistd.h>
#include <semaphore.h>

int main() {
    sem_t  sem;
                  if (sem_init(&sem, 1, 0) == -1) return 1;
                  sem_destroy(&sem);;
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for POSIX semaphores in libpthread

----------------------------------------
checking for struct msghdr.msg_control

----------------------------------------
checking for ioctl(FIONBIO)

----------------------------------------
checking for struct tm.tm_gmtoff

----------------------------------------
checking for struct dirent.d_namlen

objs/autotest.c: In function 'main':
objs/autotest.c:8:28: error: 'struct dirent' has no member named 'd_namlen'
     struct dirent  dir; dir.d_namlen = 0;
                            ^
objs/autotest.c:9:41: error: 'struct dirent' has no member named 'd_namlen'
                   printf("%d", (int) dir.d_namlen);
                                         ^
----------

#include <sys/types.h>
#include <unistd.h>
#include <dirent.h>
                  #include <stdio.h>

int main() {
    struct dirent  dir; dir.d_namlen = 0;
                  printf("%d", (int) dir.d_namlen);
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c
----------

----------------------------------------
checking for struct dirent.d_type

----------------------------------------
checking for sysconf(_SC_NPROCESSORS_ONLN)

----------------------------------------
checking for openat(), fstatat()

----------------------------------------
checking for getaddrinfo()

----------------------------------------
checking for psol

In file included from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/chromium/src/base/memory/scoped_ptr.h:100:0,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/base/scoped_ptr.h:26,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/html/html_element.h:24,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/html/html_parse.h:34,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/net/instaweb/htmlparse/public/html_parse.h:20,
                 from objs/autotest.cc:5:
/temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/chromium/src/base/memory/scoped_ptr.h:134:29: warning: invalid use of incomplete type 'class scoped_ptr<C>'
   MOVE_ONLY_TYPE_FOR_CPP_03(scoped_ptr, RValue)
                             ^
/temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/chromium/src/base/move.h:198:31: note: in definition of macro 'MOVE_ONLY_TYPE_FOR_CPP_03'
   struct rvalue_type : public type { \
                               ^
In file included from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/base/scoped_ptr.h:26:0,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/html/html_element.h:24,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/html/html_parse.h:34,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/net/instaweb/htmlparse/public/html_parse.h:20,
                 from objs/autotest.cc:5:
/temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/chromium/src/base/memory/scoped_ptr.h:133:7: note: definition of 'class scoped_ptr<C>' is not complete until the closing brace
 class scoped_ptr {
       ^
In file included from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/chromium/src/base/memory/scoped_ptr.h:100:0,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/base/scoped_ptr.h:26,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/html/html_element.h:24,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/html/html_parse.h:34,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/net/instaweb/htmlparse/public/html_parse.h:20,
                 from objs/autotest.cc:5:
/temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/chromium/src/base/memory/scoped_ptr.h:278:29: warning: invalid use of incomplete type 'class scoped_array<C>'
   MOVE_ONLY_TYPE_FOR_CPP_03(scoped_array, RValue)
                             ^
/temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/chromium/src/base/move.h:198:31: note: in definition of macro 'MOVE_ONLY_TYPE_FOR_CPP_03'
   struct rvalue_type : public type { \
                               ^
In file included from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/base/scoped_ptr.h:26:0,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/html/html_element.h:24,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/html/html_parse.h:34,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/net/instaweb/htmlparse/public/html_parse.h:20,
                 from objs/autotest.cc:5:
/temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/chromium/src/base/memory/scoped_ptr.h:277:7: note: definition of 'class scoped_array<C>' is not complete until the closing brace
 class scoped_array {
       ^
In file included from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/chromium/src/base/memory/scoped_ptr.h:100:0,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/base/scoped_ptr.h:26,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/html/html_element.h:24,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/html/html_parse.h:34,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/net/instaweb/htmlparse/public/html_parse.h:20,
                 from objs/autotest.cc:5:
/temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/chromium/src/base/memory/scoped_ptr.h:403:29: warning: invalid use of incomplete type 'class scoped_ptr_malloc<C, FreeProc>'
   MOVE_ONLY_TYPE_FOR_CPP_03(scoped_ptr_malloc, RValue)
                             ^
/temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/chromium/src/base/move.h:198:31: note: in definition of macro 'MOVE_ONLY_TYPE_FOR_CPP_03'
   struct rvalue_type : public type { \
                               ^
In file included from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/base/scoped_ptr.h:26:0,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/html/html_element.h:24,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/pagespeed/kernel/html/html_parse.h:34,
                 from /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/net/instaweb/htmlparse/public/html_parse.h:20,
                 from objs/autotest.cc:5:
/temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/chromium/src/base/memory/scoped_ptr.h:402:7: note: definition of 'class scoped_ptr_malloc<C, FreeProc>' is not complete until the closing brace
 class scoped_ptr_malloc {
       ^
/tmp/ccSeoaWQ.o: In function `base::BasicStringPiece<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::BasicStringPiece(char const*)':
autotest.cc:(.text._ZN4base16BasicStringPieceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEC2EPKc[_ZN4base16BasicStringPieceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEC5EPKc]+0x1f): undefined reference to `base::internal::StringPieceDetail<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::StringPieceDetail(char const*)'
/tmp/ccSeoaWQ.o: In function `net_instaweb::HtmlParse::ParseText(base::BasicStringPiece<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&)':
autotest.cc:(.text._ZN12net_instaweb9HtmlParse9ParseTextERKN4base16BasicStringPieceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZN12net_instaweb9HtmlParse9ParseTextERKN4base16BasicStringPieceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x29): undefined reference to `base::internal::StringPieceDetail<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::size() const'
autotest.cc:(.text._ZN12net_instaweb9HtmlParse9ParseTextERKN4base16BasicStringPieceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZN12net_instaweb9HtmlParse9ParseTextERKN4base16BasicStringPieceINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x38): undefined reference to `base::internal::StringPieceDetail<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::data() const'
collect2: error: ld returned 1 exit status
----------

#include <sys/types.h>
#include <unistd.h>

#include "net/instaweb/htmlparse/public/html_parse.h"
#include "net/instaweb/htmlparse/public/html_writer_filter.h"
#include "net/instaweb/util/public/string.h"
#include "net/instaweb/util/public/string_writer.h"
#include "net/instaweb/util/public/null_message_handler.h"

int main() {
    
  GoogleString output_buffer;
  net_instaweb::StringWriter write_to_string(&output_buffer);

  net_instaweb::NullMessageHandler handler;
  net_instaweb::HtmlParse html_parse(&handler);
  net_instaweb::HtmlWriterFilter html_writer_filter(&html_parse);

  html_writer_filter.set_writer(&write_to_string);
  html_parse.AddFilter(&html_writer_filter);

  html_parse.StartParse("http:example.com");
  html_parse.ParseText(
      "<html ><body ><h1 >Test</h1 ><p>Test Text</p></body></html>\n");
  html_parse.FinishParse();

  printf("parsed as: %s", output_buffer.c_str());
    return 0;
}

----------
cc -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -I /temp/ngx_pagespeed-1.7.30.1-beta/psol/include -I /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/chromium/src -I /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/google-sparsehash/src -I /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/protobuf/src -I /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/re2/src -I /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/out/Debug/obj/gen -I /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/out/Debug/obj/gen/protoc_out/instaweb -I /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/apr/src/include -I /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/aprutil/src/include -I /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/apr/gen/arch/linux/x64/include -I /temp/ngx_pagespeed-1.7.30.1-beta/psol/include/third_party/aprutil/gen/arch/linux/x64/include -o objs/autotest objs/autotest.cc -lstdc++ /temp/ngx_pagespeed-1.7.30.1-beta/psol/lib/Debug/linux/x64/pagespeed_automatic.a /temp/ngx_pagespeed-1.7.30.1-beta/psol/lib/Debug/linux/x64/libserf.a /temp/ngx_pagespeed-1.7.30.1-beta/psol/lib/Debug/linux/x64/libaprutil.a /temp/ngx_pagespeed-1.7.30.1-beta/psol/lib/Debug/linux/x64/libapr.a -lrt -pthread -lm
----------`

**Comment by oschaaf** [comment]
What happens if you try a recent version instead of 1.7.30.1?

**Comment by JediKnightChan** [comment]
I used automatic installation ` bash <(curl -f -L -sS https://ngxpagespeed.com/install)      --nginx-version latest` and succesfully installed

**Comment by oschaaf** [comment]
I'm assuming we can close this now that the latest version is installed. Feel free to re-open if not.
