### ISSUE TITLE
install ngx_pagespeed dynamic with centos-webpanel

### ISSUE THREAD

**Issue by lamariabdo** [apache/incubator-pagespeed-ngx#1612]
Hello

Please how to install ngx_pagespeed dynamic module with centos-webpanel
nginx already installed in **usr/local/nginx/**

i ran this command
bash <(curl -f -L -sS https://ngxpagespeed.com/install) \
     --nginx-version "1.14.2" \
     --dynamic \
     -a '--with-http_ssl_module                                                                                                                                                                
--with-http_realip_module                                                                                                                                                                 
--with-http_dav_module                                                                                                                                                                    
--with-http_gzip_static_module                                                                                                                                                            
--with-http_gunzip_module                                                                                                                                                                 
--with-threads                                                                                                                                                                            
--with-cc-opt="-DNGX_HTTP_HEADERS"'

then i copy and past ngx_pagespeed.so to **/etc/nginx/modules**
then i load it by **load_module modules/ngx_pagespeed.so;**

i got this error
**/etc/nginx/modules/ngx_pagespeed.so" is not binary compatible in /etc/nginx/nginx.conf:6**
 
i have 2 instance of nginx installed in 
**/etc/nginx/** and other in  **usr/local/nginx/**

**Comment by lamariabdo** [comment]
i fix it

**Followed steps**
1 run : nginx -V
2 copy  nginx version and configure arguments
3 run bash with --nginx-version "1.14.2"  and --dynamic 
4 past  configure arguments when cmd ask "Do you have any additional ./configure"
5 y for build nginx
6 n for install inginx
7 replace 
/etc/nginx/modules/ngx_pagespeed.so with ~/nginx-1.14.2/objs/ngx_pagespeed.so
/usr/sbin/nginx with ~/nginx-1.14.2/objs/nginx
8 add load_module modules/ngx_pagespeed.so to nginx.conf in /etc/nginx/
9 restart ingix
done.

**ngx pagespeed bash**
```
bash <(curl -f -L -sS https://ngxpagespeed.com/install) 
--nginx-version "1.14.2" 
--dynamic 
```


**configure arguments**
`--prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie'`

**Comment by sihyunki** [comment]
wow...thank you very much!
I have same problem with you!
