### ISSUE TITLE
Can't shard domains on HTTPS 

### ISSUE THREAD

**Issue by burumart** [apache/incubator-pagespeed-ngx#1616]
Hello,
I'm trying to shard domains on my webpage with my CDN. If I do it on HTTP version I can do it without problems, but if I do on HTTPS version the sharding ins't working. 
¿Any thoughts?

The error I've got with the sharding on debug page was:
I cannot rewrite xxxxxx for an unknown reason

 location ~ "^/pagespeed_static/" { }
  location ~ "^/ngx_pagespeed_beacon$" { }
  location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" { add_header "" ""; }

  pagespeed FetchHttps enable,allow_self_signed;

  pagespeed Allow wildcard_spec;
  pagespeed Disallow "*/customcheckout/*";
  pagespeed Domain "https://xxxxxxx";
  pagespeed ShardDomain "https://xxxxx" "https://xxxxxxx";

**Comment by oschaaf** [comment]
If https is terminated at the cdn you need to set it up to forward that information in a header and inform the module about it, see: https://www.modpagespeed.com/doc/https_support#RespectXForwardedProto

**Comment by burumart** [comment]
Hi,
thanks for your help, but that's not the case. Without that option, at least pagespeed should rewrite, because my CDN is configured to return always HTTPS.
Anyways I turned it on, without changes. 
I have the same exact configuration on another domain ( dev.kefiralia.es ) and it works perfectly, the only difference is that it's HTTP. I tried  tonnnns of different configurations with no luck.

You can check it here:
view-source:https://www.kefiralia.es/?PageSpeedFilters=+debug

**Comment by burumart** [comment]
After enabling FetchHTTPS, now I get the error 4xx status code, preventing rewriting of.
I found some post of you taking about this issue I'm going to try to debug it.. sight

**Comment by Lofesa** [comment]
Hi @burumart 
When run https://www.kefiralia.es/?PageSpeedFilters=+debug, I only see 2 mesages that contain https://kefiralia-produccion.azureedge.net related to a image that returns a 404 message.
Images from these domain are rewrited

Request URL: https://kefiralia-produccion.azureedge.net/skin/frontend/argento/default/images/xcommon.gif.pagespeed.ic.OIsm6pEKI_.webp
Request Method: GET
Status Code: 200 
Remote Address: 104.126.44.86:443
Referrer Policy: no-referrer-when-downgrade
cache-control: private, max-age=297
content-length: 5826
content-type: image/gif
date: Sun, 13 Jan 2019 12:29:38 GMT
expires: Sun, 13 Jan 2019 12:34:35 GMT
last-modified: Sat, 12 Jan 2019 19:18:11 GMT
server: nginx
status: 200
x-content-type-options: nosniff
x-page-speed: 1.11.33.4-0


But seems very strange this:
cache-control: private, max-age=297

Resources to be optimized by pagespeed need to be public cacheable and seems that 297 is too short time for an image.

**Comment by burumart** [comment]
Yes I'm doing changes. That message is irrelevant because I took off sharding configuration.

The problem still remains, that's why I posted log files.

**Comment by burumart** [comment]
Well after checking in your message, I just really don't know where that url is coming, because it's an old image sprite used. It isn't actually used on the webpage anymore. 

The rest of the resources have  public header, and the http webpage with the exact same configuration works. Besides that, sometimes the debug page don't reflect my changes in my nginx configuration file.
For example if I change the sharding domain, I don't know what kind of cache pagespeed uses.
