### ISSUE TITLE
302 then 200 causing Google Chrome redirect error

### ISSUE THREAD

**Issue by NickTheLim** [apache/incubator-pagespeed-ngx#1624]
Hello,

My NGINX server is configured as a reverse proxy server.

Occasionally and quite frequently it is returning a 302 to the same address that was requested after which it will return a 200 and load...

It seems completely random whether it will do a 302 refresh or a 200. 

Seems to only happen when pagespeed is enabled...

Any ideas? My thoughts are that page speed returns a 302 to process the modifications then when it loads it presents a 200 with the results.

Is this unavoidable?

Seems to be giving Google chrome some problems as of late - no other browsers seem affected.

**Comment by NickTheLim** [comment]
I am thinking this is just a problem with Google chrome or something...

**Comment by oschaaf** [comment]
I have never seen a similar report, and if this would be a common issue I think this tracker would be flooded with issues about it. So, at the moment I am betting my money on a configuration issue.

**Comment by oschaaf** [comment]
Html is optimized on the fly, yes.
There might be a case where the module redirects when javascript is required to render correctly, but the user-agent doesn't support javascript. It think you would observe a querystring parameter mentioning "noscript" when that happens. 

Maybe the error log configured to write debug-level entries can provide clues?

**Comment by NickTheLim** [comment]
Okay that solved it for now
