### ISSUE TITLE
WebP convertion do not work on Firefox 65

### ISSUE THREAD

**Issue by lightcoresystems** [apache/incubator-pagespeed-ngx#1628]
Hello,
I have Nginx v.1.14.2 with installed Pagespeed v.1.13.35.2-stable

My nginx config:

    pagespeed On;
    pagespeed FileCachePath "/var/cache/ngx_pagespeed/";
    pagespeed RewriteLevel PassThrough;
    pagespeed EnableFilters remove_comments,convert_gif_to_png,convert_png_to_jpeg,convert_jpeg_to_webp,convert_to_webp_animated;

Main problem is with images to webP convertion. On Chrome everything is working correctly (img urls are set to /images/xlogo.png.pagespeed.ic.MtZnP7OuFK.webp), but on firefox I have original urls - /images/logo.png).

I have FF version 65.0 (64bit), which supports webP. I can access the image with path /images/xlogo.png.pagespeed.ic.MtZnP7OuFK.webp on Firefox.
FF is sending Accept header with image/webp.

Why does it work only on Chrome?

================= Edit:
I also tried sending request via curl with Accept header set to "image/webp".. Im always getting original urls. I think this convertion works ONLY on Chrome. How does it works? Is it based on Accept header?

Regards

**Comment by Lofesa** [comment]
Duplicated with [#1857](https://github.com/apache/incubator-pagespeed-mod/issues/1857) in incubator-pagespeed-mod. Don´t work with png and gif images but yes with jpg

**Comment by lightcoresystems** [comment]
Ok now I understand. Most of my images are png, thats why I didnt see jpeg convertion. I tested this and I can confirm - jpeg files are converted do webp on FF. Waiting for full webp support.

Regards.
