### ISSUE TITLE
nginx: [emerg] "brotli_types"

### ISSUE THREAD

**Issue by hrace009** [apache/incubator-pagespeed-ngx#1637]
Hello, i just compile the module and use it with my previous nginx 1.14.2
i have setup the configuration, when i run nginx -t i got this result:
<pre><code>nginx: [emerg] "brotli_types" directive FileCachePath must be set, even for standby in /etc/nginx/nginx.conf:55</code></pre>

brotli was on from wordpress plugin W3 Total Cache
<pre><code>brotli on;
brotli_types text/css text/x-component application/x-javascript application/javascript text/javascript text/x-js text/richtext image/svg+xml text/plain text/xsd text/xsl text/xml image/bmp application/java application/msword application/vnd.ms-fontobject application/x-msdownload image/x-icon image/webp application/json application/vnd.ms-access video/webm application/vnd.ms-project application/x-font-otf application/vnd.ms-opentype application/vnd.oasis.opendocument.database application/vnd.oasis.opendocument.chart application/vnd.oasis.opendocument.formula application/vnd.oasis.opendocument.graphics application/vnd.oasis.opendocument.spreadsheet application/vnd.oasis.opendocument.text audio/ogg application/pdf application/vnd.ms-powerpoint application/x-shockwave-flash image/tiff application/x-font-ttf audio/wav application/vnd.ms-write application/font-woff application/font-woff2 application/vnd.ms-excel;
</code></pre>

**Comment by hrace009** [comment]
nvm, i have fix it.

**Comment by utags** [comment]
I face the same issue. How did you manage to fix it?

**Comment by mklooss** [comment]
just for Googling folks:
Sample Fix
`pagespeed FileCachePath              "/var/cache/pagespeed/";`
