### ISSUE TITLE
Unreadable code after turing on pagespeed mod, why?

### ISSUE THREAD

**Issue by majkimajki** [apache/incubator-pagespeed-ngx#1640]
Anyone have any idea, what might be the cause of output css/js looking likes this;

‹�����Ý}mWãF–ð÷ý†ÅR,»!™ììØ­ö¡ž°¡¡èd2à%Â.c%BòH2Ý{ûsï­w©dL’™³çÉ™i¬ªR©^nÝ÷{ë!Ê[÷ÙäfÝ±bÎØäææãýÇ7ßìÿòs+lm{ÓE:.ã,õXPúOíìö'6.ÛaX>ÎY6m±Ïó,/‹ö"°iœ²I{KVBÇ‹„ ùŸžh–žßoËnuOüíþ·ÝO†ü§Wú}ÖûÍç,Ç—W¾WÎâ"P#ƒa- Ö*Ê<†¡ dy‹yÌÊY¹Èá7ŒðŠ¾õN4ÁÇÃ§U¯Ì.àÕô®7Ž’ÞY©J>ëxêím…!ë¥Ù„]Âp}ÞëÕhð�ë—…Ÿât’}êÝ±ò »Ÿ/J6¹(ø~.’ÄˆA”Ãìªõ3ýL±ýÍåûÿÌitÏ†&>r––§P´\²Þ,+JýzŠ¯Ãè¶ ®‹C¼â½í·g‡?ÀŸŸdãÅ=¼ßõ`ŒìóÙÔÓýûb-1~Ù¸w›Mij1,8óƒ<Œ{ÙË§Iö)˜ ãé1ÑW^´(³e1Î3˜ý«^ÉŠÒË;EgîÃ”Rgm¬rŽ³à ÛÄzÙtZ°òÍ;ˆÃlg'SC–KÃ~ÒaÒø›¦¿‡b.aú—ûoOŽŒ©ë~|x§(£2ã’—^´çYHúÃÜËü~Ö¯.‹üq”0ü£g0—3(ÝCUÃ,wv<µÉår ÓîMã¼ÝÌâdâ#�kS0Œ°Dð¡A–ZÆ«¼[zá¡ÄÿWÁ¹õÌ|°³Þ€¾x(ª?ˆ…ƒƒºƒcèž||tzyóáìâøòøìôæÝÙÉÉÙ÷Ç§Áý„A—A Ë>¢P}nœ³¨dçQzÇ<õ�.Ê(/½8Øõz>J'^

**Comment by oschaaf** [comment]
Does piping the response through `unzip` when this happens show proper data?
I think your're running into what https://github.com/apache/incubator-pagespeed-mod/commit/73674e35ad1756b582d7710f957beeea9686cb59 solves. We're working on a release, but meantime you could try building/installing the latest of the `master` branch. (this is what we'll be releasing as well).
Closing this, but please re-open if that didn't solve it.
