### ISSUE TITLE
Image rewriting and cache extension not enabled, so not rewriting images in CSS

### ISSUE THREAD

**Issue by ismail-sheikh** [apache/incubator-pagespeed-ngx#1646]
Hi,
I have installed page-speed module for my website https://bucket.pk. Site is running on Apache with nginx as reverse proxy.
I have installed and configured Page speed to both nginx and Apache server (I was not sure to which server it should be installed).
Now visiting **Message History** in page speed admin at https://bucket.pk/pagespeed_admin/, i have noticed that my Page Speed is not working due to **ReWrite Permission** issues.
![PageSpeed Message History](https://user-images.githubusercontent.com/6323535/57448345-926d8500-7272-11e9-884d-97fbedafab28.png)

**What i have tried:**
I have added following directive to my site config (under apache  site-availble) file:

ModPagespeed on
ModPagespeedRewriteLevel CoreFilters
ModPagespeedEnableFilters extend_cache
ModPagespeedEnableFilters rewrite_images
ModPagespeedMapOriginDomain http://bucket.pk/ https://bucket.pk/

What i am missing. I have spent 2 days to figure it out but nothing helped. Please help me fix this. Thanks

**Comment by oschaaf** [comment]
`google.com` isn't hosted on your server, and therefore the module isn't going to attempt optimizing for that domain. It's an informational message, and not indicative of an error.
The `remembering recent failure..` messages are a little more concerning, it looks like the module isn't able to get to its inputs. Which admin console are we look at? The one from Apache or the one from Nginx.
I think you should choose where you want to run PageSpeed. If the Apache webserver is where you want it, you should configure nginx to forward the protocol in its request header, and set up mod_pagespeed to mind those: https://www.modpagespeed.com/doc/https_support#RespectXForwardedProto

**Comment by ismail-sheikh** [comment]
Hi @oschaaf , 
thanks for your response. can you please suggest which one of the servers is better to run page speed?
if i want to run PageSpeed on Apache, what will be required to configure on Nginx side. I mean should i be needed to add any of the pagespeed directives to server block of my site conf file?
