### ISSUE TITLE
CentOS 7: can't build PSOL from source

### ISSUE THREAD

**Issue by dvershinin** [apache/incubator-pagespeed-ngx#1656]
After all the stuff:

```
$ mkdir -p ~/bin
$ cd ~/bin
$ git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
$ export PATH=$PATH:~/bin/depot_tools
$ mkdir ~/mod_pagespeed
$ cd ~/mod_pagespeed
$ git clone https://github.com/pagespeed/mod_pagespeed.git src
$ gclient config https://github.com/pagespeed/mod_pagespeed.git --unmanaged --name=src
$ cd src/
$ git checkout ${BRANCH}
$ cd ..
$ gclient sync --force --jobs=1 # add --revision=xxxx for a specific git revision
$ make AR.host="$PWD/build/wrappers/ar.sh" \
       AR.target="$PWD/build/wrappers/ar.sh" \
       BUILDTYPE=Release \
       mod_pagespeed_test pagespeed_automatic_test
```

Getting:

> make: *** No rule to make target `mod_pagespeed_test'.  Stop.

No `Makefile` is created by previous commands. Tried to use  an older `gclient` (if that's what is supposed to generate it anyway) without success.

**Comment by Lofesa** [comment]
Hi @dvershinin 
Think these are outdated steps to do.
see at [https://www.modpagespeed.com/doc/build_mod_pagespeed_from_source](https://www.modpagespeed.com/doc/build_mod_pagespeed_from_source
).

For Centos 7 take account that you need to install libstdc++-static rpm as far that pagespeed link statics libraries. For latest versions of pagespeed don´t need the AR arguments

**Comment by dvershinin** [comment]
@Lofesa thank you, that's better.

The build runs without errors, but the output doesn't contain the likes of `pagespeed_automatic.a` static library (what I think I'm trying to build after all :) ).

I have libstdc++-static 4.8.5.

**Comment by dvershinin** [comment]
So I also did `install/build_psol.sh` and it worked.

**Comment by Lofesa** [comment]
Hi @dvershinin 
You can do a cd pagespeed/automatic and then make BUILDTYPE=Release all this creates the pagespeed_automatica.a in this dir

**Comment by Firegarden** [comment]
> So I also did `install/build_psol.sh` and it worked.

I am having the same problem with 

> make: *** No rule to make target `mod_pagespeed_test'. Stop

Can you please clarify what you mean. I am not a C programmer so this is a little challenging to understand.

**Comment by Lofesa** [comment]
@Firegarden Maybe is better to open a new issue other than  write in a closed one.
But anyway.... have you done the step from this https://www.modpagespeed.com/doc/build_mod_pagespeed_from_source?

**Comment by Firegarden** [comment]
Thank you I am still learning how to to use github. I am actually using this https://github.com/apache/incubator-pagespeed-ngx/wiki/building-psol-from-source and as you can see it has the same instructions as above and I get the same error.

**Comment by Firegarden** [comment]
> make: *** No rule to make target 'mod_pagespeed_test'

Just an update to this thread before I create a new issue. I have tested with instructions from https://www.modpagespeed.com/doc/build_mod_pagespeed_from_source and same error as above. I can not get passed the step make step

**Comment by Lofesa** [comment]
Try with this label `v1.14.33.1-RC1`. In these label the url was changed to apache repositories.
here the files to download https://github.com/apache/incubator-pagespeed-ngx/releases/tag/v1.14.33.1-RC1

**Comment by Firegarden** [comment]
@Lofesa as my Grandmother would say, God love you, and so I do I. 

*Success!* I tested with my build script and was able to build Nginx with your instructions on AWS M6g Graviton2 Arm processor 

```# Download and extract of PageSpeed module
echo -ne " Downloading ngx_pagespeed [..]\\r"
wget https://github.com/apache/incubator-pagespeed-ngx/archive/v1.14.33.1-RC1.zip >> /tmp/nginx-autoinstall.log 2>&1
unzip v1.14.33.1-RC1.zip >> /tmp/nginx-autoinstall.log 2>&1
cd incubator-pagespeed-ngx-1.14.33.1-RC1/ || exit 1
wget https://dist.apache.org/repos/dist/release/incubator/pagespeed/1.14.36.1/x64/psol-1.14.36.1-apache-incubating-x64.tar.gz
tar -xzvf psol-1.14.36.1-apache-incubating-x64.tar.gz >> /tmp/nginx-autoinstall.log 2>&1
```

Thank you for taking the time to answer this and I can confirm this works baby!
