### ISSUE TITLE
 Peer's Certificate issuer is not recognized

### ISSUE THREAD

**Issue by grayfolk** [apache/incubator-pagespeed-ngx#1661]
A small problem with site certificate:  
```
$ bash <(curl -f -L -sS https://ngxpagespeed.com/install) --nginx-version latest
curl: (60) Peer's Certificate issuer is not recognized.
More details here: http://curl.haxx.se/docs/sslcerts.html
```

Sure, this can be fixed with `curl -k` option, or using direct url instead of https://ngxpagespeed.com/install - https://raw.githubusercontent.com/pagespeed/ngx_pagespeed/master/scripts/build_ngx_pagespeed.sh

**Comment by oschaaf** [comment]
Oh nice catch, I'll look into that

**Comment by oschaaf** [comment]
Should be fixed, closing this.
