### ISSUE TITLE
Google is showing wrong FCP time.

### ISSUE THREAD

**Issue by akashkanaujiya** [apache/incubator-pagespeed-ngx#1673]
I tried a number of ideas to reduce my FCP time but still nothing happening, first, I was using Linode Virtual Machine with Apache, then FCP was around 3.2 Sec, but when I started using Google Virtual Machine with Nginx, FCP goes 3.7 sec, here is the screenshot of the website speed. 

Anyone can tell, is google telling right FCP?
<img width="782" alt="speed screenshot" src="https://user-images.githubusercontent.com/38814070/70977691-6f426800-20d4-11ea-8c1d-77f2174a820e.png">

**Comment by Lofesa** [comment]
And do you thing is related to the pagespeed-ngx module?
Your site don´t have installed the pagespeed module.....

**Comment by akashkanaujiya** [comment]
Is pagespeed module is important if we are using Cloudflare and cache plugin?

**Comment by Lofesa** [comment]
Hi
PageSpeed module is a software thats run in the server side with apache or nginx to optimize the web.
This forum is about this software, so if you don´t use it.... If you have a broken phone, you don´t go to the plumber to ask how repair it.
