### ISSUE TITLE
Image optimization on data-srcset

### ISSUE THREAD

**Issue by CharlesStrickland** [apache/incubator-pagespeed-ngx#1680]
Hi, 

I am trying to efficiently lazyload background images from a data-srcset like this: 
```
data-srcset="https://cdn.com/image/path/601x300/image.jpg 601w,https://cdn.com/image/path/747x373/image.jpg 747w ... "
```
and would like to convert these to .jpg files to .webp using pagespeed. I am aware that this issue has had some progress on [/incubator-pagespeed-mod/pull/1899](https://github.com/apache/incubator-pagespeed-mod/pull/1899) - is there any chance of updates to this repo to reflect said progress for the nginx build. 

Thanks!

**Comment by Lofesa** [comment]
Nginx still don´t have the latest version. [1.14.36.1](https://github.com/apache/incubator-pagespeed-mod/releases/tag/v1.14.36.1), avalaible for mod_pagespeed.
In this version a basic support for data-srcset is enabled with the PR [#1899](https://github.com/apache/incubator-pagespeed-mod/pull/1899).
The version 1.14.36.1 is public 2 days ago, so I think in no much more time the nginx version can land.

Maybe @oschaaf can say a stimated ETA for this.

**Comment by oschaaf** [comment]
I want to stress that  1.14.36.1(incubating) is not released yet, though hopefully very soon! It is still being voted on

**Comment by CharlesStrickland** [comment]
Alright, great. Thanks very much for the update!
