### ISSUE TITLE
Is it avaialble for latest version of nginx?

### ISSUE THREAD

**Issue by xcellenceit** [apache/incubator-pagespeed-ngx#1682]
Hi, 

Does the pagespeed ngx is available for latest version of nginx?

**Comment by Lofesa** [comment]
Hi
As far as you need to recompile nginx to add pagespeed module, yes.
I have working it with nginx 1.17.8

**Comment by xcellenceit** [comment]
Hi,

Can you share instructions on the same? I am new to nginx and pagespeed both and needs clear instructions on the same. 

Also, is it possible to post the docker for the latest nginx with pagespeed module for you? I am sure it will be helpful to many people using this, and results in saving a huge time for everyone.

Thanks

**Comment by Lofesa** [comment]
Hi
Maybe reading this as a start: https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source.

About docker, I don´t know nothing about it cause I don´t use it, but there is a docker here:
https://github.com/apache/incubator-pagespeed-ngx/tree/master/docker

**Comment by xcellenceit** [comment]
Thanks Lofesa, this helped. I am able to get it work with instructions you shared. Thanks again.
