### ISSUE TITLE
 Does this module not support Windows compilation? In vs 2015 or msys2 

### ISSUE THREAD

**Issue by sunnykandy** [apache/incubator-pagespeed-ngx#1683]
Does this module not support Windows compilation? In vs 2015 or msys2  Does this module not support Windows compilation? In vs 2015 or msys2, I compiled this module on the windows system and found that the compilation failed.

**Comment by Lofesa** [comment]
No. This module can´t be compiled in Windows.
There is a windows version, but I don´t know nothing abut it: https://www.iiswebspeed.com/

**Comment by sunnykandy** [comment]
thank you！
