### ISSUE TITLE
RPM-GPG-KEY-cern throw error 404 Not Found

### ISSUE THREAD

**Issue by TristanAdonai** [apache/incubator-pagespeed-ngx#1689]
Error: Failure runing 'sudo wget https://linux.web.cern.ch/linux/scientific6/docs/repository/cern/slc6X/i386/RPM-GPG-KEY-cern -O /tmp/tmp.gVlNyjcmQf/RPM-GPG-KEY-cern'

**Comment by Lofesa** [comment]
Are you using a gcc version older than the 4.8?

**Comment by TristanAdonai** [comment]
We have installed these gcc libraries:
![image](https://user-images.githubusercontent.com/60947201/82818735-c529f180-9e64-11ea-9031-5ab1c172c09a.png)
We are trying to update our installation of nginx + pagespeed

**Comment by Lofesa** [comment]
So you are using an older gcc version. The script tries to update from the scientific distro, and I think this distro as changed their download paths.
Try to update the gcc to at least the 4.8 version in some way.

**Comment by oschaaf** [comment]
Also, this change for mod pagespeed might be relevant:
https://github.com/apache/incubator-pagespeed-mod/commit/799d236227f23d9f6a7b0404055074f3150800a1

**Comment by oschaaf** [comment]
I think this is no longer an issue, closing this. Feel free to re-open if I'm wrong about that though.
