### ISSUE TITLE
pagespeed console show blank or chart without data.

### ISSUE THREAD

**Issue by ufgeorge** [apache/incubator-pagespeed-ngx#1690]
nginx version: nginx/1.18.0
pagespeed: 1.13.35.2

Install and work seems OK.
Browse admin page (/pagespeed_global_admin/statistics) is OK.
But browse console page (/pagespeed_global_admin/console), always show blank page or sometimes chart without data.

I saw red error when page is blank and only 2 yellow warn when chart without data.
![1](https://user-images.githubusercontent.com/51784244/83591642-facc8a00-a58a-11ea-86ab-833a54e9debe.png)

Please help me to identify what's going on. TKX.

BTW, access these page by a ghost url defined in hosts file to prevent anyone saw it.

George

**Comment by Lofesa** [comment]
I hav the same 2 yellow warn and no red one. My console show the chart.
The probllem comes from the red message, you have some problem loading the javascript, cause some are not loaded or is loaded in the wrong order.
Accesing these url with a ghost url maybe the problem, can you try to access directly?

**Comment by ufgeorge** [comment]
![1](https://user-images.githubusercontent.com/51784244/83625004-e48fef80-a5c5-11ea-92b0-44ff42e3a99b.png)
I move url to an accessable url and now the chart can show.
But the data seems not right.
Cache misses: 100.00%, the others are 0.00%

But there are numbers:
![2](https://user-images.githubusercontent.com/51784244/83625282-47818680-a5c6-11ea-9b3d-9bfdb78e838f.png)

**Comment by Lofesa** [comment]
I can see in the other issue you have opened that you use memcache. There are specific numbers for that in thw statistics part.
I am not aware about statistics part of the module, so can´t tell much more about this.
Maybe @oschaaf can tell some advice here.

**Comment by oschaaf** [comment]
Is the site serving traffic? I does look like the graphs in the console are plotting actual data points. However, I think that it operates on delta's, so if there's no actual traffic, the current status may make sense.

**Comment by ufgeorge** [comment]
I have many vhost in this server and of course serving traffic.
The graph shows from global admin.

**Comment by oschaaf** [comment]
In that case, hopefully accessing the console via the vhost-specific `/pagespeed-admin` page will show more useful information.

**Comment by ufgeorge** [comment]
There is a vhost which server name is www.ekoob.com.tw
I open it to access /pagespeed-admin but in message history, I still see other's vhost message.

But at least the graph shows data seems reasonable now.
![1](https://user-images.githubusercontent.com/51784244/83637943-f5972b80-a5da-11ea-8bd8-957bedb3a871.png)

It looks like global_admin has some bug to show graph.

**Comment by ufgeorge** [comment]
I just check when use www.ekoob.com.tw to browse /pagespeed_global_admin, it shows the same graph result as /pagespeed_admin.

It looks /pagespeed_admin did not show result of this url.
How can I to see one vhost result?

**Comment by ufgeorge** [comment]
I found I have to set UsePerVhostStatistics to off;
Then I can see chart with data no matter ghost or real url, no matter /pagespeed_admin or /pagespeed_global_admin

And it will be the same data in chart at /pagespeed_admin and /pagespeed_global_admin.

So I am confused about what UsePerVhostStatistics for?
