### ISSUE TITLE
some image did not process by pagespeed

### ISSUE THREAD

**Issue by ufgeorge** [apache/incubator-pagespeed-ngx#1691]
https://www.ekoob.com.tw/?m=Homepage&c=Index&a=index&PageSpeedFilters=+debug

There are some <img> from https://doctrans-tw.eletang.com.tw did not fetch by pagespeed. But somes did fetch and url change to https://www.ekoob.com.tw/doctrans-tw

I dont see any reason why some did not.

George

**Comment by Lofesa** [comment]
Have you control over all these domains?
Are all these domains running pagespeed module?
Can you share the pagespeed config?

**Comment by ufgeorge** [comment]
Since the url https://doctrans-tw.eletang.com.tw is a standalone domain without pagespeed for only store images and not the same as my main url https://www.ekoob.com.tw

So I have below configuration
pagespeed MapProxyDomain https://$host$1/doctrans-tw/ https://doctrans-tw.eletang.com.tw;

As you can see, some images hosted on doctrans-tw.eletang.com.tw can be rewrite, but some can't.
And I cannot see anything from debug.

That is why I am asking for help.

below is my pagespeed configuration
`## PageSpeed configurations
pagespeed on;
pagespeed ProcessScriptVariables all;
pagespeed FetchWithGzip off;
#pagespeed XHeaderValue "Powered By google_pagespeed";
#pagespeed FetchHttps enable;

## PageSpeed filter settings
pagespeed RewriteLevel CoreFilters;
pagespeed RespectVary off;
pagespeed DisableRewriteOnNoTransform off;
pagespeed NoTransformOptimizedImages on;
pagespeed SupportNoScriptEnabled false;
pagespeed ModifyCachingHeaders on;
pagespeed ListOutstandingUrlsOnError on;
pagespeed MaxCacheableContentLength -1;
pagespeed CreateSharedMemoryMetadataCache "/var/cache/ngx_pagespeed/" 51200;
pagespeed FileCachePath "/var/cache/ngx_pagespeed/";
pagespeed FileCacheSizeKb            1024000;
pagespeed FileCacheCleanIntervalMs   3600000;
pagespeed FileCacheInodeLimit        500000;
pagespeed LRUCacheKbPerProcess     8192;
pagespeed LRUCacheByteLimit        16384;
pagespeed HttpCacheCompressionLevel 9;
pagespeed InlineResourcesWithoutExplicitAuthorization Script,Stylesheet;
pagespeed LazyloadImagesAfterOnload on;
pagespeed LoadFromFileCacheTtlMs 604800000;

## Speed up PageSpeed by storing it in the super duper fast memcached
#pagespeed MemcachedThreads 1;
pagespeed MemcachedServers "10.3.0.5:11211";

## PageSpeed admin pages configuration
pagespeed UsePerVhostStatistics on;
pagespeed Statistics on;
pagespeed StatisticsLogging on;
pagespeed StatisticsLoggingIntervalMs 60000;
pagespeed StatisticsLoggingMaxFileSizeKb 1024;
pagespeed MessageBufferSize 100000;
pagespeed LogDir /var/log/pagespeed;
pagespeed StatisticsPath /ngx_pagespeed_statistics;
pagespeed GlobalStatisticsPath /ngx_pagespeed_global_statistics;
pagespeed MessagesPath /ngx_pagespeed_message;
pagespeed ConsolePath /pagespeed_console;
pagespeed AdminPath /pagespeed_admin;
pagespeed GlobalAdminPath /pagespeed_global_admin;

pagespeed StatisticsDomains Allow server1.eletang.com.tw;
pagespeed GlobalStatisticsDomains Allow server1.eletang.com.tw;
pagespeed MessagesDomains Allow server1.eletang.com.tw;
pagespeed ConsoleDomains Allow server1.eletang.com.tw;
pagespeed AdminDomains Allow server1.eletang.com.tw;
pagespeed GlobalAdminDomains Allow server1.eletang.com.tw;

pagespeed StatisticsDomains Allow server2.eletang.com.tw;
pagespeed GlobalStatisticsDomains Allow server2.eletang.com.tw;
pagespeed MessagesDomains Allow server2.eletang.com.tw;
pagespeed ConsoleDomains Allow server2.eletang.com.tw;
pagespeed AdminDomains Allow server2.eletang.com.tw;
pagespeed GlobalAdminDomains Allow server2.eletang.com.tw;

## PageSpeed Cache Purge
pagespeed EnableCachePurge on;
pagespeed PurgeMethod PURGE;
pagespeed DownstreamCacheRewrittenPercentageThreshold 95;
pagespeed EnableFilters lazyload_images;
pagespeed EnableFilters dedup_inlined_images;

pagespeed EnableFilters remove_comments;
pagespeed EnableFilters move_css_to_head;
pagespeed EnableFilters move_css_above_scripts;
pagespeed EnableFilters prioritize_critical_css;
pagespeed EnableFilters inline_google_font_css;

pagespeed EnableFilters remove_quotes;

pagespeed EnableFilters collapse_whitespace;
pagespeed EnableFilters in_place_optimize_for_browser;
#pagespeed EnableFilters elide_attributes;
pagespeed EnableFilters insert_dns_prefetch;
pagespeed EnableFilters hint_preload_subresources;

pagespeed MapProxyDomain https://$host$1/doctrans-tw/ https://doctrans-tw.eletang.com.tw;
pagespeed MapProxyDomain https://$host$1/doctrans-tw1/ https://doctrans-tw.oss-cn-shenzhen.aliyuncs.com;
pagespeed MapProxyDomain https://$host$1/sourceimg/ https://source.eletang.com;
#pagespeed LoadFromFile "https://$host$1/Public" "$document_root/Public";
#pagespeed LoadFromFile "https://$host$1/Templates" "$document_root/Templates";
#pagespeed LoadFromFile "https://$host$1/Theme" "$document_root/Theme";

pagespeed LoadFromFile "https://$host$1/" "$document_root/";
pagespeed LoadFromFileRuleMatch disallow .*;
pagespeed LoadFromFileRuleMatch allow \.(ico|pdf|swf|eot|woff|woff2|ttf|otf|css|js|jpeg|jpg|png|gif|svg|svgz|mpg|mpeg|mp3|m4a|m4v|mp4|ogg|wmv|mov|mng|3gpp|3gp|webp|webm|flv|avi|asx|asf)(\?.*)?$ps_dollar;
`

**Comment by Lofesa** [comment]
From the resource headers I can see you are using cloudflare with some optimizations enabled.
Can you try to bypass the cloudflare cache? You can put cloudflare in develop mode or disable their cache puting the dns for the site as bypass.
The problem comes from the lazyload_images filter, if you try:
https://www.ekoob.com.tw/?m=Homepage&c=Index&a=index&PageSpeedFilters=+debug,-lazyload_images
all images get loaded.
Images in the slider get loaded by a js script, maybe this interfere with the js that lazyload.images put in it.
Other issue I can see is that some images are loaded by jquery. Files loaded by a jscript snipet are not rewrited, so you have some images loaded from doctrans-tw.eletang.com.tw w/o rewriten it

**Comment by ufgeorge** [comment]
I bypass cloudflare cache of doctrans-tw.eletang.com.tw now.

https://www.ekoob.com.tw/?m=Homepage&c=Index&a=index&PageSpeedFilters=+debug,-lazyload_images
This URL will cause rewrited image 404 but non-rewrite image can show but still no rewrite.

**Comment by Lofesa** [comment]
I found that images that show have a mesage in the debug "<!--Cache-control: no-transform, preventing rewriting of ...." and images that don´t show have a debug mesage like "<!--Resource headers are preventing rewriting of...."
So a thing to check is the origin headers. I can´t check cause i get a intermitent forbbiden mesage when a try to fecht a image from https://doctrans-tw.eletang.com.tw, maybe the origin server is returning intermitent 403?
Anyway, after a bunch of page refresh I get all images with 200, and rewrited by pagesped but in the next hit gave 404 again.


![Captura](https://user-images.githubusercontent.com/22342793/83639883-a84f9580-a5ab-11ea-8679-058d1d0c8fbf.jpg)

With a original image I get a 200

![Captura](https://user-images.githubusercontent.com/22342793/83640637-b0f49b80-a5ac-11ea-9bc0-5f0e9506e10f.jpg)

But when I refresh the page get a 403

![Captura1](https://user-images.githubusercontent.com/22342793/83640665-c073e480-a5ac-11ea-82c2-9a416397bacb.JPG)

**Comment by ufgeorge** [comment]
If you get image from https://doctrans-tw.eletang.com.tw and get 403, that is correct since the server has a whitelist and allow access from those url in the list and prevent any other server to access it.

But what I want is to rewrite https://doctrans-tw.eletang.com.tw to https://www.ekoob.com.tw/doctrans-tw , and it shoud be accessed from www.ekoob.com.tw/doctrans-tw

The result now is some images can be rewrite url and get image ok, but some images can't rewrite and still get them from doctrans-tw.eletang.com.tw

**Comment by ufgeorge** [comment]
Now I change the whitelist to allow direct link to the image without refrer url.
You should not see 403 now.

**Comment by ufgeorge** [comment]
I decide to disable memcache first. Let's see how it goes.

**Comment by Lofesa** [comment]
Now I see it is working, only some images in css files don´t exists like:
https://www.ekoob.com.tw/Public/Images/ui-icons_ffd27a_256x240.png
https://www.ekoob.com.tw/Public/Images/ui-bg_diagonals-thick_20_666666_40x40.png
and some more, all from https://www.ekoob.com.tw/Public/Images/

and other css files can´t be optimized cause pagespeed is unable to improbe it
https://www.ekoob.com.tw/Public/css/app/style.css
ttps://www.ekoob.com.tw/Public/css/jquery-ui-1.10.4.min.css

**Comment by ufgeorge** [comment]
other images can´t be optimized cause are loaded by javascript snipet:
>>> Is there any way to rewrite url this kind of image?
My goal is change url from doctrans-tw.eletang.com.tw to www.ekoob.com.tw/doctrans-tw

**Comment by Lofesa** [comment]
No. Files (images or whatever file type) loaded by javascript get untouched by pagespeed module, like files pagespeed don´t know about it (*.ico, *.svg..), maybe in these files the domain can be rewrited.

**Comment by ufgeorge** [comment]
One more question.
So image load by javascript can not be lazyload by pagespeed also?

**Comment by Lofesa** [comment]
No. No lazyload... none of the filters work on it, unless you have enabled IPRO. If IPRO is enabled, some optimization can be doned but w/o rewriting the url, I will say, image can be converted to webp format, but in the url the jpg extension still here, no pagespeed in the url.. and the work is done on the fly.
pagespeed InPlaceResourceOptimization on
https://www.modpagespeed.com/doc/system#ipro

**Comment by ufgeorge** [comment]
OK. I am new guy of pagespeed...My statistics shows ipro is working.
![1](https://user-images.githubusercontent.com/51784244/83841399-5b96c680-a733-11ea-903b-7f760993eb87.png)

But how do I know laze load image is working on my web site?

**Comment by Lofesa** [comment]
Well... the images from other domains other than your own domain are not touched by pagespeed at all, even not by IPRO, so the images loaded by a javascript from the docs-trans domain can´t be optimized. If the images where loaded by javascript from your own domain, then the images can be optimized by IPRO.
Lazyload_images filter add a class to the images and a javascript snipet to do the work, and add a blank image as a placeholder.
Lazyload filter takes some hits to work because the filter need some info from images, these info is gatered by the beacons. Basically, pagespeed need to determine if the image is on the viewport or not and then add the class and the javascript, until pagespeed does not determine if the image in in the viewport you can´t see it lazyloaded.
