### ISSUE TITLE
Resources not rewritten because of restrictive Cache-Control headers: 59.79%

### ISSUE THREAD

**Issue by ufgeorge** [apache/incubator-pagespeed-ngx#1698]
I saw my pagespeed console and "Resources not rewritten because of restrictive Cache-Control headers: 59.79%".
I guess it is too much.

But how can I know which resources need to review?

**Comment by Lofesa** [comment]
Maybe using debug mode in url:
`https://mysite.com/?PageSpeedFilters=+debug`
this put debug messages in the html code.
In general, restrictive Cache-Control headers are those that make resources not public cacheable, like:
`cache-control: private`
