### ISSUE TITLE
Resource 79? How to know which one?

### ISSUE THREAD

**Issue by ufgeorge** [apache/incubator-pagespeed-ngx#1701]
I got error message from HTML:
Resource 79 https://csstc.cssa.org.tw/?m=Course&amp;c=Index&amp;a=index&amp;course_id=7715:19732: Unrecoverable CSS parse error or resource contains closing style tag

How do I know which resource is resource 79? I search whole html, no other "resource 79"...

**Comment by Lofesa** [comment]
The resource with error is the url you have posted, ths url returns a error and get a redirection.

**Comment by ufgeorge** [comment]
> The resource with error is the url you have posted, ths url returns a error and get a redirection.

Hi,
The URL to see this error is https://csstc.cssa.org.tw/?m=Course&c=Index&a=index&course_id=7715

As you can see the error is just switch "&" to "&amp;".
The url in message is the same as load url. (I guess url in message shows is just because pagespeed)

And this url is not a css file, Error message is CSS parse error. That's why I ask which css file it means!

**Comment by Lofesa** [comment]
I can see:
Resource 79 https://csstc.cssa.org.tw/?m=Course&amp;c=Index&amp;a=index&amp;course_id=7715:19621: Computed OK
If this is not ok and fires a error, this is related to a inlined snipet, not to a external file. You can see when a external file is referenced in this message, the message tell you what external file is:
https://csstc.cssa.org.tw/Public/fonts/mdi/css/materialdesignicons.min.css?20200807: Computed OK
