### ISSUE TITLE
Cache-control: no-transform after pagespeed rewrite img

### ISSUE THREAD

**Issue by ufgeorge** [apache/incubator-pagespeed-ngx#1702]
I got message from HTML
"Cache-control: no-transform, preventing rewriting of https://csstc.cssa.org.tw/Templates/1/assets/images/xclose.png.pagespeed.ic.Sq8THYCWeI.webp"

The header shows "cache-control: max-age=31536000,no-transform"

The question is
This file is created by pagespeed.
My nginx already configure
`    location ~* \.(jpg|jpeg|png|css|js|ico|webp|svg)$ {  
        expires 365d;
    add_header Cache-Control "public";  
    }
`

Why it still "Cache-control: no-transform"?
How do I prevent it?

**Comment by Lofesa** [comment]
Maybe you have set:
`pagespeed DisableRewriteOnNoTransform off;`
see the doc here:
https://www.modpagespeed.com/doc/configuration#notransform

**Comment by ufgeorge** [comment]
My pagespeed config already include it.
Also
pagespeed DisableRewriteOnNoTransform off;
pagespeed NoTransformOptimizedImages on;

Not sure does NoTransformOptimizedImages effect it?

**Comment by Lofesa** [comment]
Yes. `pagespeed NoTransformOptimizedImages on;` set the notransform cache-control header.
See the doc: https://www.modpagespeed.com/doc/reference-image-optimize#NoTransformOptimizedImages

**Comment by ufgeorge** [comment]
`pagespeed NoTransformOptimizedImages off;` 
I wont see the message anymore.
But from doc, I think it is better to set it on to prevent other proxy to recompress it since it already optimized.

Am I correct?

**Comment by Lofesa** [comment]
Maybe yes
