### ISSUE TITLE
deadline_exceeded 

### ISSUE THREAD

**Issue by ufgeorge** [apache/incubator-pagespeed-ngx#1703]
I saw message from debug.
`
`
What does it mean?

**Comment by oschaaf** [comment]
Those are informational messages, and nothing to worry about. It means that some optimizations didn't make it in time for a page render. On the next render/page load it's probably going to be ready.

**Comment by ufgeorge** [comment]
I see lots of time browse these pages. But still saw the same message at the same position.
It looks those js always cannot be optimized.

Is there anyway to improve it?

**Comment by ufgeorge** [comment]
`pagespeed RewriteDeadlinePerFlushMs 20;`
It can extend rewrite timeout from default 10ms to 20ms.

**Comment by oschaaf** [comment]
> `pagespeed RewriteDeadlinePerFlushMs 20;`
> It can extend rewrite timeout from default 10ms to 20ms.

Sure but it does make browsers wait a little longer. But 20ms still seems reasonable to me!
