### ISSUE TITLE
nginx reload, memcache clean?

### ISSUE THREAD

**Issue by ufgeorge** [apache/incubator-pagespeed-ngx#1704]
Pagespeed runs with memcached.
After running a period of time, I run nginx -s reload.
And I notice memory usage drop 1GB. It will getting higher slowly.

The situation seems memcache cleaned when nginx reload.

Why this happen?
I use memcached because there will be 2nd nginx with pagespeed. If one nginx reload cause cache clean, then the effect of pagespeed is not good.

**Comment by Lofesa** [comment]
Sure is memcached ?
If I remember pagespeed does nothing to evict records on memcached. 
Have you configured shared memory and the in-memory LRU cache? These caches are in ram memory and are dependent of the nginx process, so if these process are cleared, these in-memory cache are cleared too.
When you do the nginx reload what show this command:
`ps aux | grep memcached`

**Comment by ufgeorge** [comment]
OK. At "Physical Caches", there is no decrease of total items of memcached when nginx reload. So it is not because memcache.

My pagespeed configutation below about shared memory and LRU.
`pagespeed DefaultSharedMemoryCacheKB 51200;`
`pagespeed LRUCacheKbPerProcess     8192;`
`pagespeed LRUCacheByteLimit        16384;`

Looks shared memory is 50MB. Not sure how much memory used by LRU.
But totally 1GB drop seems not possible.

I see my other VM which does not install pagespeed. There is almost no decrease of memory when nginx reload.
Maybe it is not relate to pagespeed...

**Comment by Lofesa** [comment]
Or maybe yes. Take a look to the nginx process size before/after the reload.
`ps aux | grep nginx`
