### ISSUE TITLE
JavaScript minification failures: 1.41%

### ISSUE THREAD

**Issue by ufgeorge** [apache/incubator-pagespeed-ngx#1705]
I see console: JavaScript minification failures: 1.41% (doc)

After review debug, there are several 
`<!--JS not inlined since it&#39;s bigger than 2048 bytes-->`
But not find other error yet.

I want to know does this "bigger than 2048" calculate into "JavaScript minification failures"?

**Comment by Lofesa** [comment]
I have not rewived the code, but I think is not related.
The messages about not being inlined are because you have enabled the inline_javascript filter but have the default max size of js code that can be inlined (you can set the max size with `ModPagespeedJsInlineMaxBytes bytes`).
But the statitics are about js minification, that is for some reason pagespeed can´t minify a js file, maybe it can´t do it because the file is allready minified. or whatever other reason.

**Comment by ufgeorge** [comment]
OK. Then I need to find them! TKX.

May I know in your experience, how many bytes is good for inline of js?

**Comment by ufgeorge** [comment]
I found some like:
`<link href="Public/A.fonts,,_mdi,,_css,,_materialdesignicons.min.css,,q20200812+css,,_font-awesome.min.css,,q20200812,Mcc.stCZxiFe4O.css.pagespeed.cf.PBZCmqTAvd.css" rel=stylesheet><!--deadline_exceeded for filter CacheExtender--><!--deadline_exceeded--><!--deadline_exceeded--><!--deadline_exceeded-->`

It looks like JS minification error.
What it means "deadline exceed" ?

**Comment by oschaaf** [comment]
> I found some like:
> `<link href="Public/A.fonts,,_mdi,,_css,,_materialdesignicons.min.css,,q20200812+css,,_font-awesome.min.css,,q20200812,Mcc.stCZxiFe4O.css.pagespeed.cf.PBZCmqTAvd.css" rel=stylesheet><!--deadline_exceeded for filter CacheExtender--><!--deadline_exceeded--><!--deadline_exceeded--><!--deadline_exceeded-->`
> 
> It looks like JS minification error.
> What it means "deadline exceed" ?

Nothing to worry about, it's an informational message, which indicates content was flushed out to the browser in order to not make it wait for full optimization to be ready, aiming to avoid making that browser wait for too long. Next page loads will resolve.

**Comment by oschaaf** [comment]
Closing as this isn't really an issue with the module

**Comment by ufgeorge** [comment]
I found `pagespeed RewriteDeadlinePerFlushMs 20;` can reduce deadlines.

**Comment by ufgeorge** [comment]
@oschaaf 
After one day turn RewriteDeadlinePerFlushMs to 20ms, "deadline exceed" info is much lower than before.
But "JavaScript minification failures" still the same...

I almost read all debug html but not find relate info!
Is there any other place I can see which js files has this problem?
