### ISSUE TITLE
<!--CSS rewrite failed: Cannot improve https://www.ekoob.com.tw/Public/css/app/style.css-->

### ISSUE THREAD

**Issue by ufgeorge** [apache/incubator-pagespeed-ngx#1706]
I saw this in debug
`<!--CSS rewrite failed: Cannot improve https://www.ekoob.com.tw/Public/css/app/style.css-->`

Is there any reason or what I should do with this file?
TKX.

**Comment by Lofesa** [comment]
Pagespeed when can´t improve any resource let it untouched.

**Comment by ufgeorge** [comment]
I thought some bad things cause it...
Looks it might be just pagespeed does not need to rewrite.
