### ISSUE TITLE
memcached full?

### ISSUE THREAD

**Issue by ufgeorge** [apache/incubator-pagespeed-ngx#1707]
I saw physical cache below, does it mean cache full, I better locate higher memory for memcached?
bytes:                 942245336
bytes_read:            169050056368
bytes_written:         229701605873
cmd_get:               38488776
cmd_set:               27626073
connection_structures: 194
curr_connections:      156
curr_items:            228412
evictions:             1172883
get_hits:              25532004
get_misses:            12956772
limit_maxbytes:        1073741824
pointer_size:          64
rusage_system:         5059684543
rusage_user:           64
threads:               4
total_connections:     11075
total_items:           21034088

**Comment by oschaaf** [comment]
Bigger is always better if resources allow. I remember that ideally, as a thumb rule, around 3-4X the size of the original assets of the site should suffice to store variants for different user-agents in cache.
