### ISSUE TITLE
git.apache.org times out when cloning 

### ISSUE THREAD

**Issue by eilandert** [apache/incubator-pagespeed-ngx#1722]
Situation:
When cloning/pulling with recursive submodules git://git.apache.org times out.

Background:
git.apache.org is permanently down after a crash a while ago, repositories are moved to github. but internal links are probably never changed.

Assessment:
In ngx_pagespeed/testing-dependencies/mod_pagespeed/.gitmodules are still some old links to git.apache.org

Recommendation:
cd ngx_pagespeed/testing-dependencies/mod_pagespeed
git submodule set-url third_party/apr/src https://github.com/apache/apr.git
git submodule set-url third_party/httpd24/src https://github.com/apache/httpd.git
git submodule set-url third_party/aprutil/src https://github.com/apache/apr-util.git
git submodule set-url third_party/httpd/src https://github.com/apache/httpd.git
git submodule set-url third_party/serf/src https://github.com/apache/serf.git

git pull --recurse-submodules

**Comment by Lofesa** [comment]
What version are you trying to clone or from where get you these software?
These git files come from pagespeed for pache and the url are updated more than a year ago:
https://github.com/apache/incubator-pagespeed-mod/blob/v1.14.36.1/.gitmodules

**Comment by eilandert** [comment]
from master actually, new clone. never had this problem until now

**Comment by eilandert** [comment]
its actually no concern anymore, since I discovered I had to use the other repository to build psol!  *ouch*

**Comment by Lofesa** [comment]
Or use a pre-build psol library
