### ISSUE TITLE
What is the latest build release for nginx? 

### ISSUE THREAD

**Issue by eric-mathison** [apache/incubator-pagespeed-ngx#1726]
According to the Release notes, the version should be 1.14.36.1. But when getting the URL:
```
https://github.com/apache/incubator-pagespeed-ngx/archive/v1.14.36.1.tar.gz 
```
it resolves with a 404. What version is recommended to use?

**Comment by Lofesa** [comment]
Hace you searchhed for this same issue?
Read #1656

**Comment by oschaaf** [comment]
Closing as a duplicate of https://github.com/apache/incubator-pagespeed-ngx/issues/1730
