### ISSUE TITLE
Failed to install nginx pagespeed module due SSL expired Certificate

### ISSUE THREAD

**Issue by pablo-silveira** [apache/incubator-pagespeed-ngx#1747]
I noticed that the certificate SSL of https://ngxpagespeed.com/ expired on April 13th.
So I receiving an error when executing `bash <(curl -k -f -L -sS https://ngxpagespeed.com/install)` .

Do you have any estimated to renewal this certificate or some workaround to solve this issue?

Thanks!

**Comment by Lofesa** [comment]
Hi @pablo-silveira 

Noticed the same yesterday and send a message to @oschaaf and tell me maybe today the certificate will be updated.

**Comment by oschaaf** [comment]
Should be fixed!

**Comment by pablo-silveira** [comment]
Thank you all!
