### ISSUE TITLE
Modify remote configurations on the fly

### ISSUE THREAD

**Issue by Hackintoshcorp** [apache/incubator-pagespeed-ngx#1754]
Hi, how and is it even possible to change the name of the remote configuration file for example by $host variable.

normal config setting:
pagespeed RemoteConfigurationUrl https://example.com/remote.conf;
dynamic config setting:
pagespeed RemoteConfigurationUrl https://$host/remote.conf;

I tried everything but cant get it to work. Do you know how?

**Comment by oschaaf** [comment]
Do you also have `pagespeed ProcessScriptVariables on;`

```
http {
    pagespeed ProcessScriptVariables on;
    server {
        pagespeed LoadFromFileMatch "^https?://$host/" "$document_root/";
    }
}
```

**Comment by Hackintoshcorp** [comment]
As I understand this loads HTML, CSS and other stuff it does not load remote config. I need to load remote config https://www.modpagespeed.com/doc/config_filters#remote-configuration
