### ISSUE TITLE
Eror compiling with nginx 1.23.1 

### ISSUE THREAD

**Issue by crywolfy** [apache/incubator-pagespeed-ngx#1764]
Hi there im trying to compile module with nginx 1.23.1 and im getting the folowing output

nginx version: nginx/1.23.1
Debian 10 Buster

just whanna do the dynamic module
./configure --with-compat --add-dynamic-module=./incubator-pagespeed-ngx

        ./incubator-pagespeed-ngx/src/ngx_pagespeed.cc
./incubator-pagespeed-ngx/src/ngx_pagespeed.cc: In function ‘ngx_int_t net_instaweb::{anonymous}::ps_set_cache_control(ngx_http_request_t*, char*)’:
./incubator-pagespeed-ngx/src/ngx_pagespeed.cc:407:36: error: request for member ‘elts’ in ‘r->ngx_http_request_s::headers_out.ngx_http_headers_out_t::cache_control’, which is of pointer type ‘ngx_table_elt_t*’ {aka ‘ngx_table_elt_s*’} (maybe you meant to use ‘->’ ?)
   if (r->headers_out.cache_control.elts == NULL) {
                                    ^~~~
./incubator-pagespeed-ngx/src/ngx_pagespeed.cc:408:35: error: cannot convert ‘ngx_table_elt_t**’ {aka ‘ngx_table_elt_s**’} to ‘ngx_array_t*’
     ngx_int_t rc = ngx_array_init(&r->headers_out.cache_control, r->pool,
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/core/ngx_core.h:65,
                 from src/http/ngx_http.h:13,
                 from ./incubator-pagespeed-ngx/src/ngx_pagespeed.h:33,
                 from ./incubator-pagespeed-ngx/src/ngx_pagespeed.cc:26:
src/core/ngx_array.h:32:29: note:   initializing argument 1 of ‘ngx_int_t ngx_array_init(ngx_array_t*, ngx_pool_t*, ngx_uint_t, size_t)’
 ngx_array_init(ngx_array_t *array, ngx_pool_t *pool, ngx_uint_t n, size_t size)
                ~~~~~~~~~~~~~^~~~~
./incubator-pagespeed-ngx/src/ngx_pagespeed.cc:415:22: error: cannot convert ‘ngx_table_elt_t**’ {aka ‘ngx_table_elt_s**’} to ‘ngx_array_t*’
       ngx_array_push(&r->headers_out.cache_control));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/core/ngx_core.h:65,
                 from src/http/ngx_http.h:13,
                 from ./incubator-pagespeed-ngx/src/ngx_pagespeed.h:33,
                 from ./incubator-pagespeed-ngx/src/ngx_pagespeed.cc:26:
src/core/ngx_array.h:27:35: note:   initializing argument 1 of ‘void* ngx_array_push(ngx_array_t*)’
 void *ngx_array_push(ngx_array_t *a);
                      ~~~~~~~~~~~~~^
./incubator-pagespeed-ngx/src/ngx_pagespeed.cc: In function ‘bool net_instaweb::{anonymous}::ps_get_cache_control(ngx_http_request_t*, GoogleString*)’:
./incubator-pagespeed-ngx/src/ngx_pagespeed.cc:439:74: error: request for member ‘elts’ in ‘r->ngx_http_request_s::headers_out.ngx_http_headers_out_t::cache_control’, which is of pointer type ‘ngx_table_elt_t*’ {aka ‘ngx_table_elt_s*’} (maybe you meant to use ‘->’ ?)
   auto ccp = static_cast<ngx_table_elt_t**>(r->headers_out.cache_control.elts);
                                                                          ^~~~
./incubator-pagespeed-ngx/src/ngx_pagespeed.cc:444:59: error: request for member ‘nelts’ in ‘r->ngx_http_request_s::headers_out.ngx_http_headers_out_t::cache_control’, which is of pointer type ‘ngx_table_elt_t*’ {aka ‘ngx_table_elt_s*’} (maybe you meant to use ‘->’ ?)
   for (ngx_uint_t i = 0; i < r->headers_out.cache_control.nelts; i++) {
                                                           ^~~~~
make[1]: *** [objs/Makefile:1342: objs/addon/src/ngx_pagespeed.o] Error 1
make[1]: Leaving directory '/home/crywolfy/kernel/nginx1.23.1/nginx-1.23.1'
make: *** [Makefile:16: modules] Error 2

what im doing wrong ?

**Comment by crywolfy** [comment]
If you can explain better, did not understand what to check nginx or pagespeed, with commands will be better, i did try to compile it on nginx 1.23.3 and the same... :(

**Comment by skygunner** [comment]
git master tree is the main git repository branch. 

To build from the source code in the master branch for the newer nginx version, you can use something like this:

`sudo apt install git wget -y

NPS_BRANCH=master
PSOL_VER=1.14.36.1
BUILDING_HOME=/tmp

echo "Downloading ngx_pagespeed src from git and PSOL src from apache ..."
cd $BUILDING_HOME
git clone -b $NPS_BRANCH https://github.com/apache/incubator-pagespeed-ngx.git ngx_pagespeed-${NPS_BRANCH}
cd ngx_pagespeed-${NPS_BRANCH}
wget -v https://downloads.apache.org/incubator/pagespeed/${PSOL_VER}/x64/psol-${PSOL_VER}-apache-incubating-x64.tar.gz
tar -xzvf psol-${PSOL_VER}-apache-incubating-x64.tar.gz

cd /your-nginx-source-code-path
./auto/configure --add-dynamic-module=${BUILDING_HOME}/ngx_pagespeed-${NPS_BRANCH} --with-compat
make modules`

**Comment by crywolfy** [comment]
They don't work on me, but this worked flawesly
https://github.com/apache/incubator-pagespeed-ngx/issues/1756#issuecomment-1204517605

Thanks.

**Comment by skygunner** [comment]
It is off topic but I want to mention that by enabling the corefilters level on my testing 2 cpu shared vps, 
loader.io test showing the response time has been slowed by almost 100% even with just 100 concurrent connections. 
Might be better to use it on vps with at least 4 cores?
